### ISSUE TITLE
Feature: expose versioning in LanceDB Node / Rust

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#1007]
### SDK

Node

### Description

Add methods on `Table` for switching between versions, such as:

* `checkout(version)` switch to time travel mode
* `checkout_latest()` return to latest mode
* `version` to get the current version number

These are already expose in Python.

**Comment by westonpace** [comment]
I believe this has been done in the new API.  For rust:

https://docs.rs/lancedb/latest/lancedb/table/struct.Table.html#method.checkout
https://docs.rs/lancedb/latest/lancedb/table/struct.Table.html#method.checkout_latest
https://docs.rs/lancedb/latest/lancedb/table/struct.Table.html#method.version

For nodejs:

https://lancedb.github.io/lancedb/js/classes/Table/#checkout
https://lancedb.github.io/lancedb/js/classes/Table/#checkoutlatest
https://lancedb.github.io/lancedb/js/classes/Table/#version

**Comment by universalmind303** [comment]
it looks like the methods are implemented in the new lancedb sdk, but some of the docstrings are incorrect. They appear to be copy/pasted from the rust docstrings

```ts
  /**
   * Retrieve the version of the table
   *
   * LanceDb supports versioning.  Every operation that modifies the table increases
   * version.  As long as a version hasn't been deleted you can `[Self::checkout]` that
   * version to view the data at that point.  In addition, you can `[Self::restore]` the
   * version to replace the current table with a previous version.
   */
  async version(): Promise<number> {
    return await this.inner.version();
  }
```
