### ISSUE TITLE
bug(rust): open non-exist table shouldn't create the table in object store

### ISSUE THREAD

**Issue by BubbleCal** [lancedb/lancedb#1019]
### LanceDB version

lastest

### What happened?

I'm trying to test open a non-exist table, but then I found that the dir was created and `table_names()` returns the non-exist table

### Are there known steps to reproduce?

```rust
db.open_table("invalid_table").execute().await;
assert_eq!(db.table_names().await.unwrap().len(), 0);
```

**Comment by eddyxu** [comment]
Closed in https://github.com/lancedb/lance/pull/2215
