### ISSUE TITLE
bug(node): error when using local storage

### ISSUE THREAD

**Issue by flaviut** [lancedb/lancedb#1078]
### LanceDB version

v0.4.11

### What happened?

In short, I called

```
lancedb.connect({
  "uri": "/var/folders/j5/zqtb_vtx6p166jkfgpkcrfd80000gp/T/lance-db-test-hoMBti"
})
```

Then I got an exception:

```
Error: Invalid credentials configuration
    at LocalConnection.createTableImpl (...node_modules/vectordb/src/index.ts:715:35)
    at LocalConnection.createTable (...node_modules/vectordb/src/index.ts:676:12)
```

things seem to work if I do this:

```
lancedb.connect({
  awsCredentials: undefined,
  awsRegion: undefined,
  "uri": "/var/folders/j5/zqtb_vtx6p166jkfgpkcrfd80000gp/T/lance-db-test-hoMBti"
})
```

**Comment by wjones127** [comment]
Hi @flaviut. I'm not able to reproduce this. Could you share more information about your system. What operating system are you using?

**Comment by wjones127** [comment]
Nevermind, I can reproduce. It doesn't fail on `lancedb.connect` for me, it fails when I call `createTable`.

**Comment by wjones127** [comment]
Okay, if you are only passing the URI, you can simply write:

```js
lancedb.connect("/var/folders/j5/zqtb_vtx6p166jkfgpkcrfd80000gp/T/lance-db-test-hoMBti")
```

And it will work. It's just broken when you pass an object.

**Comment by flaviut** [comment]
Got it, thank you for reproducing! I was having a lot of trouble reproducing outside of my unit tests as well, and thought it might have been an environment variable issue, but you're right that the `createTable` is where the error really comes from.
