### ISSUE TITLE
bug(python): Slow Performance on S3-backed storage

### ISSUE THREAD

**Issue by mrocklin** [lancedb/lancedb#1088]
### What happened?

I'm doing a query on an S3 backed LanceDB and observing multi-minute query times.

```python
import os
os.environ["AWS_DEFAULT_REGION"] = "us-west-2"

import lancedb
db = lancedb.connect(
    "s3://openscapes-scratch/mrocklin/lance", 
    region="us-west-2",
)
tbl = db.open_table("arxiv")  # this is around 8 GiB and 2 million rows

from sentence_transformers import SentenceTransformer
model = SentenceTransformer("all-MiniLM-L6-v2")

results = tbl.search(  # This search command takes two minutes
    model.encode("black holes are cold")
).limit(3).to_pandas().text.tolist()
```

The final search query takes two minutes.  I'm not very close to the data (it's in us-west and I'm in Texas) but I am on fiber internet.  It takes around 30s when run from a VM in that region.  This is longer than I was expecting.  Maybe something is wrong?  My next step is to look into creating an index.  Any advice would be welcome.

**Comment by wjones127** [comment]
Hi @mrocklin, could you should your parameters for your vector index?

See: [Building an ANN Index](https://lancedb.github.io/lancedb/ann_indexes/)

**Comment by mrocklin** [comment]
I haven't created an index.  I guess that's the problem?  For good performance on S3 at this size we should plan to have an index?

**Comment by wjones127** [comment]
> For good performance on S3 at this size we should plan to have an index?

In general, I think the threshold at which an index becomes worthwhile is around 5-10 thousand vectors. Brute force KNN search is very compute intensive and requires reading all the vectors from S3 (for 2 million 384-dimensional vectors, that's nearly 3GB). So millions of vectors is definitely a scale where an index is necessary for usable performance.

Note that S3 is a high-latency system, so even with an index it's hard to get better than 300 - 500ms.

**Comment by mrocklin** [comment]
OK, after running the following:

```python
    tbl.create_index(num_partitions=256, num_sub_vectors=96)
```

This runs in 4-5s

```python
results = tbl.search(
    model.encode("...")
).limit(3).to_pandas().text.tolist()
```

(model encoding runs in ~100ms)

**Comment by wjones127** [comment]
> This runs in 4-5s

That sounds more like it. Do you see the query times get lower (< 1s) for warm queries (after the index has been cached)?

Also, you should see lower latency if you select fewer columns (using `.select()`).

**Comment by mrocklin** [comment]
Yeah, it gets down to around 1.5s for a new query, and then if I repeat exactly the same query it gets to 300ms.

**Comment by kevinlsu** [comment]
wanted to followup here that i solved my problem by running compaction, dropping my 30s query (already was using Prefiltering to lower the searchable rows to <100) to 1s
