### ISSUE TITLE
Doc issue: Possible typo/error in documentation

### ISSUE THREAD

**Issue by raghavdixit99** [lancedb/lancedb#1111]
### Description

`. code-block::python` should'nt be rendered there , maybe a minor syntax issue in markdown

### Link

https://lancedb.github.io/lancedb/python/python/#lancedb.table.Table.create_scalar_index

**Comment by AyushExel** [comment]
@raghavdixit99 can you take this up? Closing this here and adding it to a new global ticker

**Comment by raghavdixit99** [comment]
Yes pls tag me
