### ISSUE TITLE
FTS search index crashes as lance cannot infer vector field

### ISSUE THREAD

**Issue by natcharacter** [lancedb/lancedb#1124]
### What happened?

If you have an index with only FTS and no vectors, searching without passing through an vector_column_name crashes. However, it works fine if you pass in an empty string for 

### Are there known steps to reproduce?

Create any index with only an FTS index and no vector index. Then run:

`table.search(query="hi",query_type="fts").to_list()`

```
You'll get the following traceback.:
Traceback (most recent call last):
 File "/app/test.py", line 5, in <module>
 table.search(query="hi",query_type="fts").to_list()
 File "/usr/local/lib/python3.10/site-packages/lancedb/table.py", line 1329, in search
  vector_column_name = inf_vector_column_query(self.schema)
 File "/usr/local/lib/python3.10/site-packages/lancedb/util.py", line 189, in inf_vector_column_query
  raise ValueError(
ValueError: There is no vector column in the data. Please specify the vector column name for vector search
```

Passing vector_column_name='' fixes it, so easy workaround for now, but is a bit confusing.

**Comment by changhiskhan** [comment]
Should be a quick fix. I'll see if I can throw up a PR tonight
