### ISSUE TITLE
Feature: Unable to add a docId as an integer in the table schema

### ISSUE THREAD

**Issue by pkundu25** [lancedb/lancedb#1126]
### SDK

Python

### Description

This is regarding the schema of LanceDB table. I was trying to add a new docId as an integer in the schema, but I wasn’t able to do so while creating the vector store using the method LanceDB. from_documents() as I couldn’t pass docId as a parameter! I am not sure if it is possible to add a docId apart from id as a string in the schema. The idea is to recognize each and every documents after chunking so that we can selectively delete any documents from the vector store.

Refer to link (https://python.langchain.com/docs/integrations/vectorstores/lancedb)

**Comment by pkundu25** [comment]
@AyushExel , as discussed, could you please look into the issue. Thanks.

**Comment by AyushExel** [comment]
@raghavdixit99

**Comment by raghavdixit99** [comment]
@pkundu25  my latest PR solves this - https://github.com/langchain-ai/langchain/pull/19284

**Comment by pkundu25** [comment]
@raghavdixit99 , I had gone through the PR resolution. But I am still facing issue when I was trying with LanceDB.from_documents() method as I am getting a KeyError: 'Field "docId" does not exist in schema'. Though I created a schema as below:
index,vector,text,id,docId
0,"[ 0.32421875  0.35546875  0.625      ...  0.6796875  -1.375
  0.3046875 ]",Hello World,1,1
Just to give you the context I am using PDF files for creating vector index. As I mentioned earlier, I wanted to have docId as scalar index (integer) so that I can use that to select a particular document or a list of documents to be able to delete them selectively. Could you please guide me here with example code. Thanks.
