### ISSUE TITLE
bug(python): Passing limit of `None` or 0 or -1 to `search().limit()` fails

### ISSUE THREAD

**Issue by jiahuei** [lancedb/lancedb#1151]
### LanceDB version

v0.6.5

### What happened?

Passing limit of `None` or 0 or -1 to `search().limit()` fails.
It should have returned all results (no limit).

### Are there known steps to reproduce?

```python
import lancedb
import numpy as np
import pyarrow as pa


embed_len = 3
lance_db = lancedb.connect("db/test-lance-0")
table = lance_db.create_table(
    "documents",
    schema=pa.schema(
        [pa.field("text", pa.utf8()), pa.field("embed", pa.list_(pa.float16(), embed_len))]
    ),
)
table.add([dict(text="Prime minister", embed=np.ones([embed_len], dtype=np.float16))])
table.create_fts_index(["text"])
table.checkout_latest()

# These work
print(table.search(np.ones([embed_len], dtype=np.float16), "embed").limit(1).to_list())
print(table.search("minister", "text").limit(1).to_list())

# These all fail
print(table.search(np.ones([embed_len], dtype=np.float16), "embed").limit(None).to_list())
print(table.search(np.ones([embed_len], dtype=np.float16), "embed").limit(0).to_list())
print(table.search(np.ones([embed_len], dtype=np.float16), "embed").limit(-1).to_list())
# Traceback (most recent call last):
#   File "test_lance.py", line 28, in <module>
#     print(table.search(np.ones([embed_len], dtype=np.float16), "embed").limit(0).to_list())
#   File ".../lib/python3.10/site-packages/lancedb/query.py", line 302, in to_list
#     return self.to_arrow().to_pylist()
#   File ".../lib/python3.10/site-packages/lancedb/query.py", line 527, in to_arrow
#     return self.to_batches().read_all()
#   File ".../lib/python3.10/site-packages/lancedb/query.py", line 545, in to_batches
#     query = Query(
#   File ".../lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
#     __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
# pydantic_core._pydantic_core.ValidationError: 1 validation error for Query
# k
#   Input should be a valid integer [type=int_type, input_value=None, input_type=NoneType]
#     For further information visit https://errors.pydantic.dev/2.4/v/int_type
print(table.search("minister", "text").limit(None).to_list())
print(table.search("minister", "text").limit(0).to_list())
print(table.search("minister", "text").limit(-1).to_list())
# Traceback (most recent call last):
#   File "test_lance.py", line 45, in <module>
#     print(table.search("minister", "text").limit(None).to_list())
#   File ".../lib/python3.10/site-packages/lancedb/query.py", line 302, in to_list
#     return self.to_arrow().to_pylist()
#   File ".../lib/python3.10/site-packages/lancedb/query.py", line 682, in to_arrow
#     row_ids, scores = search_index(
#   File ".../lib/python3.10/site-packages/lancedb/fts.py", line 195, in search_index
#     results = searcher.search(query, limit)
# TypeError: argument 'limit': 'NoneType' object cannot be interpreted as an integer

```

**Comment by wjones127** [comment]
> It should have returned all results (no limit).

@jiahuei What would "all results" mean? Conceptually, the search sorts the table by distance to your query, then takes the top `k` rows. If we returned "all result", wouldn't that just be every row in the table?

**Comment by jiahuei** [comment]
I'm just referring to the docs where it says "Call this method and pass 0, a negative value, or None to remove the limit."

https://lancedb.github.io/lancedb/python/python/#lancedb.query.LanceQueryBuilder.limit

**Comment by wjones127** [comment]
I see. We can add that back then.

**Comment by jiahuei** [comment]
Thanks! I actually agree with having a limit rather than returning everything, I'm just pointing out the discrepancy with the docs and type hint.
On the other hand, I am much more interested in having the `offset` parameter exposed. Currently I am calling the underlying dataset `lance_table._dataset.to_table(columns=columns, limit=limit, offset=offset).to_pylist()`

**Comment by wjones127** [comment]
> On the other hand, I am much more interested in having the offset parameter exposed.

Noted. That shouldn't be hard to add at the same time we fix this.

**Comment by otsneh** [comment]
+1, running into this as well. Any update on this? @wjones127

**Comment by wjones127** [comment]
> +1, running into this as well. Any update on this?

Sorry for not replying to this for a while. Which part are you +1'ing? The having the `limit` be removable? Or having an `offset` parameter?

I'm going to create a second issue for the offset idea, for clarity.

**Comment by wjones127** [comment]
Issue created over here: https://github.com/lancedb/lancedb/issues/1555

**Comment by wjones127** [comment]
As far as allowing no limit for ANN queries: We could implement this by writing something like:

```python
if self._limit is None or self._limit < -1:
    if self._nearest is not None:
        limit = table.count_rows()
    else:
        limit = None
```

`limit` is required in Lance, but setting it to the total number of rows would work just fine. However, because of the way IVF-PQ indices work, you won't actually get all results *unless* you also pass `n_probes` equal to number of IVF partitions in the index. Because of this, I'm wary of even implementing this kind of API. You can still get these results by manually passing these parameters. Trying to do this for users might cause confusion.

Maybe the better solution would be to write a clearer error message that `limit` is required for ANN / KNN queries. And we could describe that in the docs, as suggested.
