### ISSUE TITLE
bug(node): @ lancedb version 0.4.14 missing for a few platforms on NPM

### ISSUE THREAD

**Issue by sestinj** [lancedb/lancedb#1163]
### LanceDB version

v0.4.14

### What happened?

v0.4.14 depends on @ lancedb/<platform> version 0.4.14, which doesn't exist for many platforms, leading to an error on `npm install`. This will affect almost anyone who has installed `vectordb`, as "^0.4.x" will resolve to 0.4.14.

NPM search shows that only a couple of them have a version 0.4.14

<img width="883" alt="Screenshot 2024-03-28 at 8 31 37 AM" src="https://github.com/lancedb/lancedb/assets/33237525/9d5bd27e-989d-4677-8527-9fad5bdafb29">

Just downgrading to 0.4.12 is a perfectly fine solution for now.

And thanks for all the work that you do! When I found LanceDB it was exactly what we needed, and has played its role perfectly since then : )

**Comment by wjones127** [comment]
Yeah it looks like there is a bug in our CI scripts. The `vectordb` for x86 on Mac and Linux did not build. I think it's because there was a name collision in upload artifacts. Looking into this now.

**Comment by sestinj** [comment]
thanks for the quick fix!
