### ISSUE TITLE
bug(python): PanicException: attempt to divide by zero when creating index

### ISSUE THREAD

**Issue by happy15** [lancedb/lancedb#1182]
### LanceDB version

v0.6.6

### What happened?

PanicException: attempt to divide by zero when creating index with:
```
tbl.create_index(metric='cosine')
```
or
```
tbl.create_index()
```
the table has ~6000 doc and full scan search works well.

### Are there known steps to reproduce?

New to lancedb and followed steps similar to readme.md on https://github.com/lancedb/lancedb.

The full scan search works well, but a little bit slow, so tried to add an index.

**Comment by changhiskhan** [comment]
what kind of latency are you seeing? Full scan should still be very fast at that scale.
If you inserted one row at a time instead of in one batch, you'll get much better performance from doing a compaction (`lancedb_table.to_lance().optimize.compact_files()`)

**Comment by changhiskhan** [comment]
the divide by zero error is probably from the default parameters which has too many partitions for your dataset. At 6k vectors, num_partitions should be like 2 or 4. But again, if you're seeing bad latency at such low scale, it's more likely compaction than indexing that will help
