### ISSUE TITLE
bug(python): Cohere reranker AttributeError when getting relavance_score from results

### ISSUE THREAD

**Issue by hyorea1** [lancedb/lancedb#1196]
### LanceDB version

v0.6.6

### What happened?

For _rerank method for Cohere reranker, the value "result" has no attribute "relevance_score" 

    def _rerank(self, result_set: pa.Table, query: str):
        docs = result_set[self.column].to_pylist()
        results = self._client.rerank(
            query=query,
            documents=docs,
            top_n=self.top_n,
            model=self.model_name,
        )  # returns list (text, idx, relevance) attributes sorted descending by score

        indices, scores = list(
            zip(*[(result.index, result.relevance_score) for result in results])
        )  # tuples
        result_set = result_set.take(list(indices))
        # add the scores
        result_set = result_set.append_column(
            "_relevance_score", pa.array(scores, type=pa.float32())
        )

        return result_set

AttributeError: 'tuple' object has no attribute 'relevance_score'

**Comment by AyushExel** [comment]
Thanks for reporting. This is broken due to a change in cohere API. I raised a ticket here to confirm this https://github.com/cohere-ai/cohere-python/issues/446
I'll get to fixing it today EOD
