### ISSUE TITLE
Potential Violation of AGPL-3.0 License Terms in `lancedb/lancedb`

### ISSUE THREAD

**Issue by glenn-jocher** [lancedb/lancedb#1197]
@changhiskhan @AyushExel et al.,

I am writing to bring to your attention a significant issue regarding non-compliance with the GNU Affero General Public License v3.0 [(AGPL-3.0)](https://github.com/ultralytics/ultralytics/blob/main/LICENSE) that governs the https://github.com/ultralytics/ultralytics project.

Today I discovered numerous instances within https://github.com/lancedb/lancedb where the Ultralytics AGPL-3.0 code that I've personally written has been copied in to this project and "re-licensed" under Apache 2.0. One example is that **every one of the 17 functions in the LanceDB python/utils/general.py file presented as LanceDB Apache 2.0 code is actually my own Ultralytics AGPL-3.0 code copied 6 months ago** in PR https://github.com/lancedb/lancedb/pull/538 and illegally re-licensed by LanceDB as Apache 2.0 code.

I haven't looked elsewhere and discovered this by accident when searching for a function in Ultralytics I found it twice, once where it should be and a second to my surprise of the exact same function in the LanceDB Python package. This is very disappointing to see and clearly does not adhere to the critical conditions set forth by the AGPL-3.0. Specifically, the following key points have not been respected:

1. **Same License**: The AGPL-3.0 is a strong copyleft license that requires any modified versions or derivative works of the licensed software to be made available under the same AGPL-3.0 license. This condition ensures that all subsequent modifications and derived works continue to provide the same freedoms as the original work.

2. **Disclose Source**: There is a lack of proper disclosure regarding the source of the AGPL-3.0 licensed code used within the project. The AGPL-3.0 mandates that the complete source code of licensed works and modifications, including larger works that incorporate a licensed work, be made available. This is crucial for maintaining transparency and allowing users to exercise their rights under the license, including studying, modifying, and distributing the code.

3. **License and Copyright Notice**: It appears that copyright and license notices have not been consistently preserved or included in accordance with the AGPL-3.0 requirements. These notices are essential for informing users of their rights under the license, as well as acknowledging the contributions and copyright of the original authors.

AGPL-3.0 is designed to ensure that the freedom to use, modify, and share software is preserved and protected, especially for software that is distributed as part of a larger work. Compliance with the license's conditions is not optional but a legal obligation that accompanies the benefits of using AGPL-3.0 licensed software.

I understand the challenges that can come with managing open-source license compliance, especially in large and complex projects. However, it is crucial for the sustainability of open-source software that these legal frameworks are respected.

Thank you for your prompt attention to this matter.

**Comment by AyushExel** [comment]
Hey Glenn, I've opened a PR to remove all the concerned functions. My bad, I didn't realise based on our discussion that that those util functions are under GPL 3.0 license.

**Comment by AyushExel** [comment]
Also we can delete the concerned functions from git history completely by purging it. This should remove any 'conflicts' due to those functions
