### ISSUE TITLE
Invalid notebook link on the website

### ISSUE THREAD

**Issue by gssakash** [lancedb/lancedb#121]
On the official documentation page over [here](https://lancedb.github.io/lancedb/#complete-demos), Shouldn't the link for the Youtube Transcripts Search be pointing to [this](https://github.com/lancedb/lancedb/blob/main/notebooks/youtube_transcript_search.ipynb) link found on Github?

**Comment by changhiskhan** [comment]
Thanks! Your PR I just merged fixed the link I thought? Or that was somewhere else in the docs?

**Comment by gssakash** [comment]
It only fixed the link on the documentation. On the website, the user gets redirected [here](https://lancedb.github.io/notebooks/youtube_transcript_search.ipynb) which gives you a 404 page.
So maybe you'll need to add the Jupyter notebook to a separate page on the website or maybe update the link to this Github link instead - https://github.com/lancedb/lancedb/blob/main/notebooks/youtube_transcript_search.ipynb

**Comment by jaichopra** [comment]
Thanks for calling this out. We will get the fix in on the website.
