### ISSUE TITLE
bug(python): search function is throwing error when querying lancedb tables which have indices

### ISSUE THREAD

**Issue by Mohan6677** [lancedb/lancedb#1216]
### LanceDB version

v0.6.6

### What happened?

i am getting this error when i am querying lancedb  from a fastapi backend service

> thread 'lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq/utils.rs:63:5:
> sub_vector idx: 96, num_sub_vectors: 96
> note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
> thread 'lance_background_thread' panicked at /home/runner/work/lance/lance/rust/lance/src/utils/tokio.rs:34:24:
> called Result::unwrap() on an Err value: RecvError(())
> thread 'lance-cpu' panicked at /home/runner/work/lance/lance/rust/lance-index/src/vector/pq/utils.rs:63:5:
> sub_vector idx: 96, num_sub_vectors: 96
> Io error: Execution error: External error: Execution error: ExecNode(Take): thread panicked: task 54 panicked

this is how i am querying the lancedb table:-

```
tbl_conn.search(query=query_vector)
            .limit(body.size)
            .select(source_fields)
            .metric(body.distance_function)
            .to_list()
```
i have 3 indices created on this table for l2, dot and cosine each.

this is how i created lancedb table for a partitioned parquet dataset containting 2M embeddings and 6.3gb size

```
db = lancedb.connect("<path>")
arrow_tbl = pq.read_table("s3://<>")
tbl = db.create_table(
            table.name, arrow_tbl, exist_ok=True
        )
        print(tbl.schema)
        if index:
            for distance_type in table.distance_type:
                tbl.create_index(metric=distance_type)
```

**Comment by eddyxu** [comment]
Hey, @Mohan6677 what is the dimension of your dataset? This is like some mismatch between dimension and `num_sub_vectors`?

**Comment by Mohan6677** [comment]
@eddyxu  i am currently have embeddings with 512 dimensions in lancedb.

**Comment by eddyxu** [comment]
Yea, 512 % 96 is not dividable. Lets try `num_sub_vector=32`?

**Comment by Mohan6677** [comment]
Ok. Let me try

**Comment by Mohan6677** [comment]
@eddyxu   That worked. Probably we should update the docs accordingly. Thanks for the quick turnaround on this. Really Appreciate it.
