### ISSUE TITLE
 No matching distribution found for lancedb==0.6.10

### ISSUE THREAD

**Issue by kingzcheung** [lancedb/lancedb#1236]
Although the file declares support for Python 3.8,
https://github.com/lancedb/lancedb/blob/431f94e5644936e67298e81285c76d8fd1858d29/python/pyproject.toml#L21.
But i received the following error:

```
ERROR: Could not find a version that satisfies the requirement lancedb==0.6.10 (from -r /app/requirements.txt (line 3)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.2.0, 0.2.1, 0.2.2, 0.2.4, 0.2.5, 0.2.6, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.5.6, 0.5.7)
ERROR: No matching distribution found for lancedb==0.6.10 (from -r /app/requirements.txt (line 3))
```

and python 3.9 is ok.

**Comment by chebbyChefNEQ** [comment]
Hi,

What's the platform/OS you are running on?

**Comment by kingzcheung** [comment]
> Hi,
> 
> What's the platform/OS you are running on?

arm  linux

**Comment by chebbyChefNEQ** [comment]
What's the distro?

Context: we only release manylinux 2_24 for aarch64 linux.

**Comment by kingzcheung** [comment]
> What's the distro?
> 
> Context: we only release manylinux 2_24 for aarch64 linux.

 Ubuntu 20.04.6 LTS aarch64 GNU/Linux

**Comment by chebbyChefNEQ** [comment]
`manylinux 2_24` requires ubuntu 21+

but looks like `manylinux2014` has better compatibility. We can try switching over to `2014`. `2_24` seems to be EOL anyways

**Comment by chebbyChefNEQ** [comment]
https://github.com/lancedb/lancedb/issues/1241

**Comment by kingzcheung** [comment]
> `manylinux 2_24` requires ubuntu 21+
> 
> but looks like `manylinux2014` has better compatibility. We can try switching over to `2014`. `2_24` seems to be EOL anyways

This is a very strange thing, and I later bypassed this issue through other means. It runs very well
