### ISSUE TITLE
Feature(nodejs):  `Table.search` function for `lancedb` sdk

### ISSUE THREAD

**Issue by universalmind303** [lancedb/lancedb#1256]
### SDK

Node

### Description

both the python sdk, and the older js `vectordb` sdk have a `search` function on the table class. 

`tbl.search(query)`.

There does not appear to be an equivalent in the newer `lancedb` sdk

**Comment by wjones127** [comment]
`Table.query()` is the equivalent of this. I just looked, and I think we already have feature parity here, so I'm closing this.

**Comment by universalmind303** [comment]
@wjones127 There isn't full feature parity. In python you don't need to manually embed the query. 


```py
query = "greetings"
table.search(query).limit(1)
```

```js
const query = await func.computeQueryEmbeddings("greetings");
    
await table.query().nearestTo(query).limit(1)
```
