### ISSUE TITLE
Doc: "Youtube Transcript Search QA Bot" documentation is incorrect. Needs small fix for it to work.

### ISSUE THREAD

**Issue by nehiljain** [lancedb/lancedb#1268]
### Description

I was running the "Youtube Transcript Search QA Bot" example.

```
def embed_func(c):    
    rs = client.embeddings.create(input=c, model="text-embedding-ada-002")
    return [rs.data[0].embedding]
```

Is incorrect and leads to error.
```ArrowInvalid: Added column's length must match table's length. Expected length 100 but got length 1```

Fix is to 

```
return [
        data.embedding
        for data in rs.data
    ]
```

### Link

https://lancedb.github.io/lancedb/notebooks/youtube_transcript_search/#create-embedding-function

**Comment by AyushExel** [comment]
Thanks.. Merged the PR
