### ISSUE TITLE
bug(python):  LanceDB S3 Data Source Index Not Exist Issue for Hybrid Search With Colbert Reranking

### ISSUE THREAD

**Issue by mohdjaved99** [lancedb/lancedb#1272]
### LanceDB version

^0.6.10

# What happened?

```
 File "/Users/mohd.javed/Documents/go/GitHub/service/.venv/lib/python3.11/site-packages/lancedb/query.py", line 245, in to_df
    return self.to_pandas()
           ^^^^^^^^^^^^^^^^
  File "/Users/mohd.javed/Documents/go/GitHub/service/.venv/lib/python3.11/site-packages/lancedb/query.py", line 262, in to_pandas
    tbl = self.to_arrow()
          ^^^^^^^^^^^^^^^
  File "/Users/mohd.javed/Documents/go/GitHub/service/.venv/lib/python3.11/site-packages/lancedb/query.py", line 810, in to_arrow
    fts_results = fts_future.result()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.11/3.11.7_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mohd.javed/Documents/go/GitHub/service/.venv/lib/python3.11/site-packages/lancedb/query.py", line 670, in to_arrow
    raise FileNotFoundError(
FileNotFoundError: Fts index does not exist. Please first call table.create_fts_index(['<field_names>']) to create the fts index.
```
we connect vectorDB from our s3 bucket like this.
lancedb.connect("s3://bucket_name/path_name")
and then query
self.table.search(query, query_type="hybrid").limit(10).rerank(reranker=self.reranker).to_df()
Our As we are using hybrid search with colbert reranking and it internally uses both FTS and vector search and then normalise to give the best chunks on the basis of relevance score. As it uses FTS search so we need to create a FTS index in the table at the time of its creation and we are already doing this.
Now as we see we already created the FTS index at the time of tables creation but still on searching we are getting the index not exists error.

# Root Cause
I checked the internal codebase of hybrid search lancedb and this is how they check if the index exists or not

```
// get the index path
index_path = self._table._get_fts_index_path()
// check if the index exist
 if not Path(index_path).exists():
            raise FileNotFoundError(
                "Fts index does not exist. "
                "Please first call table.create_fts_index(['<field_names>']) to "
                "create the fts index."
            )
```
_get_fts_index_path returns s3://bucket_name/path_name/table_name.lance/_indices/tantivy which is fine and this path exists in the s3 bucket as well but the way they check path seems to be a bug in lancedb library.
Path(index_path).exists() works only for checking local system path and not s3 as our lancedb source is S3 bucket.

### Are there known steps to reproduce?

1. Use S3 as data store for lanceDB 
2. Use Hybrid Search With Colbert Reranking.
3. Run Query.

**Comment by wjones127** [comment]
Hi @mohdjaved99. LanceDB hybrid search relies on there being an full-text search (FTS) index. Unfortunately, FTS indices aren't supported on object stores such as S3 yet. Adding support for this is on our roadmap https://github.com/lancedb/lancedb/issues/1121 for this year though. I hope to have that released sometime around the end of summer.

**Comment by wjones127** [comment]
I've created a fix to make the error clearer: https://github.com/lancedb/lancedb/pull/1273

**Comment by mohdjaved99** [comment]
thanks for the response @wjones127.
