### ISSUE TITLE
Please provide better documentation for from lancedb.embeddings 

### ISSUE THREAD

**Issue by leozc** [lancedb/lancedb#128]
The helper function `with_embeddings` is a very important function. However, the usage is under-documented, could you please help to add documentation of its usage, particularly the function signature of `func`?

Another recommendation, we may want sensible default parameters.
1. wrap_api=False - by default, it is true, where making the local embedding encoder throttled.
2. Can we make it clear if the function modifies the data in place or provides a copy?

**Comment by prrao87** [comment]
Revisiting this important function: it needs to have a better docstring (with examples) to show up in the API documentation.
@changhiskhan

**Comment by AyushExel** [comment]
@changhiskhan 's last embedding function PR should have addressed most of this? Closing. Please re-open if something needs more clarity
