### ISSUE TITLE
Enable stemming and choosing tokenizer, when doing full text search in tantivy

### ISSUE THREAD

**Issue by josca42** [lancedb/lancedb#1315]
### SDK

Python

### Description

Enabling stemming and using a language specific tokenizer tend to improve recall quite a bit, when doing full text search.

Tantivy has support for this through the [tokenizer_name argument in add_text_field](https://tantivy-py.readthedocs.io/en/latest/tutorials/#building-an-index-and-populating-it).

As far as I can tell the change needed is to add tokenizer_name argument to the following [line](https://github.com/lancedb/lancedb/blob/5349e8b1db57dda7ec7c61d6ee55b81625bf3acc/python/python/lancedb/fts.py#L59)

And then add the tokenizer_name argument to the [create_fts_index](https://github.com/lancedb/lancedb/blob/5349e8b1db57dda7ec7c61d6ee55b81625bf3acc/python/python/lancedb/table.py#L1171) method.

I would personally really prefer if the argument could be exposed instead of just enabling the usage of the english stemmer. [Tantivy supports a few different language tokenizers](https://docs.rs/tantivy/latest/tantivy/tokenizer/enum.Language.html), which I think a lot of people would like to use instead of english

I can create a pull request with the suggested changes if you think it is a good idea :-).

**Comment by wjones127** [comment]
This all sounds good to me. Feel free to make a PR :)
