### ISSUE TITLE
bug(python): Reranker pyarrow compatibility update

### ISSUE THREAD

**Issue by raghavdixit99** [lancedb/lancedb#1324]
### What happened?

Getting `FutureWarning: promote has been superseded by promote_options='default'.
  combined_results = self.merge_results(vector_results, fts_results)`
  
  the issue is here , needs to be changed to `promote_options='default'` - https://github.com/lancedb/lancedb/blob/43f920182aa1de35f0055fbf48414907add493da/python/python/lancedb/rerankers/base.py#L122

**Comment by eddyxu** [comment]
This one is fixed

https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/rerankers/base.py#L49
