### ISSUE TITLE
bug(python): Cohere embedding functions use incorrect input type for query embeddings

### ISSUE THREAD

**Issue by huffmanjohnf** [lancedb/lancedb#1329]
### LanceDB version

v0.8.0

### What happened?

Cohere embeddings for search and retrieval prepend special tokens to differentiate embedding types. This is specified by `input_type` parameter in the [Cohere API](https://docs.cohere.com/reference/embed) and in the [Bedrock API for Cohere embedding models](https://docs.aws.amazon.com/bedrock/latest/userguide/model-parameters-embed.html).

Neither of the `generate_embeddings` methods in the [CohereEmbeddingFunction](https://github.com/lancedb/lancedb/blob/python-v0.8.0/python/python/lancedb/embeddings/cohere.py#L70C9-L85) and [BedrockText](https://github.com/lancedb/lancedb/blob/python-v0.8.0/python/python/lancedb/embeddings/bedrock.py#L106-L153) classes allow for the correct use of the `input_type` parameter, even though there are distinct `compute_query_embeddings` and `compute_source_embeddings` methods that could control the correct `input_type` value. The `BedrockText` class even [hardcodes the `"search_document"` input type for all embeddings](https://github.com/lancedb/lancedb/blob/python-v0.8.0/python/python/lancedb/embeddings/bedrock.py#L144-L148). This leads to a noticeable performance reduction when evaluating search and retrieval pipelines that use these LanceDB embedding functions when compared to generating the embedding vectors externally with the correct `input_type` parameter and passing the vectors into LanceDB.

I'd propose we expose the model keyword arguments, specifically `input_type` parameter to the `compute_query_embeddings` and `compute_source_embeddings` methods for specifying the correct `input_type` for each case.

- `compute_source_embeddings` methods should use `"search_document"` for encoding documents for embeddings that are stored in the database
- `compute_query_embeddings` methods should use `"search_query"` when querying the database for relevant documents.

**Comment by AyushExel** [comment]
Thanks for pointing out. Looks like input_type was introduced in embed v3. Is it also supported in v2 models? Let me test it out today add a PR to address this

**Comment by huffmanjohnf** [comment]
Yes, it was introduced in embed v3. It appears the API is backwards compatible so that `input_type` is not required for v2 models but it can still be included as a valid API call (I assume the value is simply ignored). I just tested this in the Cohere Developer Playground with `embed_english_v2` and `embed_english_v3` using the `input_type = "classification"` for both cases. You might have ideas for more thorough testing.

Let me know if you'd like me to propose a PR to the Python code. I don't think I could implement a fix for Javascript/Typescript or Rust if the same behavior is present there.

**Comment by AyushExel** [comment]
@huffmanjohnf hey, can you take a quick pass here https://github.com/lancedb/lancedb/pull/1335

**Comment by huffmanjohnf** [comment]
Looks great! I just left a few non-blocking comments. Not sure if you were just looking for some feedback or if you'll need approval from me.
