### ISSUE TITLE
bug(python): Full Text Search Index Not Updated Upon LanceTable Update

### ISSUE THREAD

**Issue by Guest400123064** [lancedb/lancedb#1365]
### LanceDB version

v0.8.0

### What happened?

Tantivy FTS index does not seem to be updated accordingly when new data points are added to the LanceTable through `Table.add` method. See the code snippet below to reproduce.

### Are there known steps to reproduce?

```
import lancedb


db = lancedb.connect("TEST_DB")

# Add some initial data, create FTS index, and add some more
table = db.create_table("TEST_TABLE", data=[{"text": "abc"}])
table.create_fts_index("text")
table.add([{"text": "def"}])

# Examine records available in LanceTable and FTS index
print(table.count_rows())  # Should be 2
print(table.search("abc", query_type="fts").to_list())  # Should give 'abc'
print(table.search("def", query_type="fts").to_list())  # Should give empty list
```

**Comment by wjones127** [comment]
Hello, thanks for trying LanceDB!

This is expected behavior right now. Auto-updating FTS indices are on our roadmap for later this year. For now, best practice is to rebuild the index once you are finished adding / updating rows.

**Comment by Guest400123064** [comment]
Oh I see! Thanks for the quick reply!
