### ISSUE TITLE
Feature: Integration with Tantivy Queries Object

### ISSUE THREAD

**Issue by alex-au-922** [lancedb/lancedb#1379]
### SDK

Python

### Description

As tantivy-py comes to version `0.22.0`, literally most of the native Tantivy queries are now available in Python (e.g. BooleanQuery, DisjunctionMaxQuery). 

While this feature might conflict with issue #849, I think the object-typed query is useful in creating more flexible queries, and even some that aren't available currently in the parsing engine (e.g. ConstQuery, DisjunctionMaxQuery) whose syntax are hard to express. Furthermore, using object-typed Tantivy queries are more maintainable and less error-prone.

Due to the existence of issue #849, here are 2 scenarios which could affect this integration:

*Scenario 1*. LanceDB adopts the true Rust-level Tantivy SDK based on issue #849:
We can only continue stick to the query parser (string type queries), or else the same problem continues with the use of `tantivy-py`.

*Scenario 2*. LanceDB continues to use the pyO3-ported Tantivy-py SDK:
The existing reranker only accepts string type inputs, which another behaviour might be needed if the object-typed Tantivy queries are accepted.

Would like to know how the team's latest consensus and idea on object-typed queries during search.

**Comment by wjones127** [comment]
> Would like to know how the team's latest consensus and idea on object-typed queries during search.

Our tentative plan is to implement our own full-text search index at the Rust level. This will be inspired by Tantivy, but not actually using it. Tantivy doesn't provide low-level enough APIs for us to have full control over how indices are written. We'll need that to support fast incremental re-indexing over Lance tables.

I think Tantivy's APIs are well designed, though. We are happy to draw inspiration there, especially for features that our users want. So we might design with an object-typed query when we start implementing an index of our own.

**Comment by alex-au-922** [comment]
This helps clarify my question. I'm looking forward to see the adoption of tantivy / lucene-type queries in LanceDB with score-based filtering!
