### ISSUE TITLE
bug(node): .select() doesn't work with upper-case column names

### ISSUE THREAD

**Issue by flaviut** [lancedb/lancedb#1385]
### LanceDB version

@lancedb/lancedb@0.5.2

### What happened?

```
import { Field, Schema as ArrowSchema, Table as ArrowTable } from 'apache-arrow'
import * as types from 'apache-arrow/type'
import * as lancedb from '@lancedb/lancedb'

const db = await lancedb.connect('./')
const table = await db.createTable('testtable',
  new ArrowTable(
    new ArrowSchema([
      new Field('pageContent', new types.Utf8()),
    ]),
  ),
  { existOk: true },
)
await table.add([{ pageContent: 'content' }])
const result = await table.query().select(['pageContent']).toArray()
expect(result).toMatchObject([{ pagecontent: 'content' }])
```

```
Error: Failed to execute query stream: lance error: LanceError(Schema): Column pagecontent does not exist, /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-core-0.12.1/src/datatypes/schema.rs:179:31
```

I expected the test to pass instead. It seems like the column names are getting incorrectly lowercased somewhere.

If I rename `pageContent` to `pagecontent`, things work OK.

**Comment by wjones127** [comment]
I think this problem is specific to the TypeScript SDK. This works fine in Python:

```python
import lancedb
import pyarrow as pa

data = pa.table({"myColumn": [1, 2, 3]})
db = lancedb.connect("./tmp")
table = db.create_table("myTable", data)
table.search().select(['myColumn']).to_arrow()
```

```
pyarrow.Table
myColumn: int64
----
myColumn: [[1,2,3]]
```

**Comment by universalmind303** [comment]
@wjones127 this seems like it's actually a bug in the rust core

```rs
    #[tokio::test]
    async fn test_select_case_sensitivity() {
        fn make_data() -> impl IntoArrow {
            let schema =
                ArrowSchema::new(vec![ArrowField::new("textField", DataType::Utf8, false)]);

            let text = StringArray::from_iter_values(vec!["a", "b", "c", "d"]);
            let schema = Arc::new(schema);
            let rb = RecordBatch::try_new(schema.clone(), vec![Arc::new(text)]).unwrap();
            Box::new(RecordBatchIterator::new(vec![Ok(rb)], schema))
        }

        let tmp_dir = tempdir().unwrap();
        let dataset_path = tmp_dir.path().join("test.lance");
        let uri = dataset_path.to_str().unwrap();
        let db = connect(uri).execute().await.unwrap();
        let table = db
            .create_table("my_table", make_data())
            .execute()
            .await
            .unwrap();
        
        let query = table
            .query()
            .select(Select::dynamic(&[("textField", "textField")]));

        let result = query.execute().await;
        assert!(result.is_ok())
    }
```

**Comment by wjones127** [comment]
Ah, so these are being interpretted as SQL strings? I assume so if it's going through `Select::Dynamic` rather than `Select::Columns`. If that's the case, then maybe wrapping in backtick will help:

```typescript
const result = await table.query().select(['`pageContent`']).toArray()
```

**Comment by universalmind303** [comment]
@wjones127 since JS always goes through `Select::dynamic` for `select([...columns])` shouldn't we just always wrap everything in backticks to be safe?

**Comment by wjones127** [comment]
> shouldn't we just always wrap everything in backticks to be safe?

No, why would we do that? If a user does `select(['columnA + columnB'])`, they want the sum of `columnA` and `columnB`, not some column named "columnA + columnB". We would need some way to tell whether the user meant the literal column name or a SQL expression. That's what the two variants in Rust mean.

**Comment by flaviut** [comment]
```
const result = await table.query().select(['`pageContent`']).toArray()
```

is a good workaround, although there is a caveat: the results objects will also have the backticks in the keys. This can further be worked around by doing the following to apply an alias:

```
const result = await table.query().select({
  pageContent: '`pageContent`'
}).toArray()
```

If I was designing this API, I'd probably go with two methods: `.select()` which accepts a list and always treats the names literally, and `.selectAs()`, which only accepts an object/map & interprets the values as SQL.

**Comment by rkunnamp** [comment]
Just adding that  merge operation fails when column names contain upper-case

```python
import pyarrow as pa
import lancedb
data = pa.table({ 
                  "C1": ["A", "B"], 
                  "C2": ["a", "b"],
                  "C3": [1, 2]
               })
db = lancedb.connect("lancedb")
db.create_table("my_table", data)
table = db.open_table("my_table")
new_data = pa.table({ 
                    "C1": ["A", "B",], 
                    "C2": ["a", "b"], 
                    "C3": [1,4]
               })
merge_builder = lancedb.merge.LanceMergeInsertBuilder(table, on=["C1", "C2"])
merge_builder.when_matched_update_all().when_not_matched_insert_all().execute(new_data)
```

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-13-bafff2e459cb>](https://localhost:8080/#) in <cell line: 1>()
----> 1 merge_builder.when_matched_update_all().when_not_matched_insert_all().execute(new_data)

2 frames
[/usr/local/lib/python3.10/dist-packages/lance/dataset.py](https://localhost:8080/#) in execute(self, data_obj, schema)
    102         reader = _coerce_reader(data_obj, schema)
    103 
--> 104         return super(MergeInsertBuilder, self).execute(reader)
    105 
    106     # These next three overrides exist only to document the methods

OSError: LanceError(IO): Schema error: No field named c1. Valid fields are "?table?"."C1", "?table?"."C2", "?table?"."C3"., /home/runner/work/lance/lance/rust/lance/src/dataset/write/merge_insert.rs:468:22


---

The same code works correctly  when the column names are in small case

**Comment by wjones127** [comment]
> Just adding that merge operation fails when column names contain upper-case

That makes sense. I think this will happen whenever the column names are interpreted as SQL identifiers.

**Comment by wjones127** [comment]
@rkunnamp I'm going to close this soon when we fix `select()`. However, `merge_insert` will take substantially more work to fix. I'll be tracking that progress in this upstream issue, if you want to follow along: https://github.com/lancedb/lance/issues/2621
