### ISSUE TITLE
ORDER BY not Applied

### ISSUE THREAD

**Issue by Pipboyguy** [lancedb/lancedb#1422]
### LanceDB version

0.9.0

### What happened?

ORDER BY clause not working as expected

### Are there known steps to reproduce?

```python
import lancedb
db = lancedb.connect("/tmp/db")

data = [
    {"id": 1, "value": 10},
    {"id": 2, "value": 5},
    {"id": 3, "value": 15},
    {"id": 4, "value": 7}
]
db.create_table("test_table", data, mode="overwrite")

print("Ascending order:")
result = db["test_table"].search().select(["id", "value"]).where("1=1 ORDER BY value ASC").to_list()
print(result)

print("\nDescending order:")
result = db["test_table"].search().select(["id", "value"]).where("1=1 ORDER BY value DESC").to_list()
print(result)
```

```
Ascending order:
[{'id': 1, 'value': 10}, {'id': 2, 'value': 5}, {'id': 3, 'value': 15}, {'id': 4, 'value': 7}]

Descending order:
[{'id': 1, 'value': 10}, {'id': 2, 'value': 5}, {'id': 3, 'value': 15}, {'id': 4, 'value': 7}]
```

**Comment by eddyxu** [comment]
The `where(...)` only apply as filter during the scan, LanceDB itself does not have `order by` capability. As it is not meant to be a full SQL engine. 

Do you have particular use case needs `Order By` that is difficult to use with DuckDB + LanceDB?

**Comment by Pipboyguy** [comment]
Makes perfect sense! I assumed that the https://lancedb.github.io/lancedb/sql/#pre-and-post-filtering datafusion functions included the full SELECT syntax.

Thanks for clarifying. If you'd like to know more about where this is coming from: https://github.com/dlt-hub/dlt/pull/1375
