### ISSUE TITLE
bug(python): Low recall on Lance IVF_HNSW_* indexes

### ISSUE THREAD

**Issue by zhidongqu-db** [lancedb/lancedb#1428]
### LanceDB version

latest 0.14.0

### What happened?

I was benchmarking different flavors of index types supported by LanceDB and found that both IVF_HNSW_SQ and IVF_HNSW_PQ have unexpected low recall on query. 

If I understand correctly Lance IVF_HNSW_* indices builds a sub-HNSW index for each IVF partition to help reduce number of IVF partitions required for large scale datasets, which is slightly different from faiss IVF_HNSW variants where a HNSW graph gets build on IVF centroids when the number of centroids gets large to help speed up retrieval latency. 

When we set `n_partitions` and `n_probe` both to 1 for Lance IVF_HNSW_* index types, it should effectively create a HNSW index with SQ/PQ quantization. 

However, when I cross compared it with popular implementation like faiss, I've noticed a significant difference in recall (~10%). The problem seem to be related to the HNSW implementation not the quantizer implementation because the recall difference between Lance IVF_PQ and IVF_HNSW_PQ also appears to be very significant with the same level of quantization applied.

### Are there known steps to reproduce?

I was able to repro this issue on a commonly used [sift10k dataset](http://corpus-texmex.irisa.fr/)

Installing dataset with 

```
wget ftp://ftp.irisa.fr/local/texmex/corpus/siftsmall.tar.gz
tar -xzvf siftsmall.tar.gz
```

Simple python script for repro
```
import lance
import pandas as pd
import numpy as np
import pyarrow as pa
import faiss
import psutil
import time
import uuid
import os

M = 32
efConstruction = 1024
nbits = 8
k = 10


def read_ivecs(fname):
  a = np.fromfile(fname, dtype="int32")
  d = a[0]
  return a.reshape(-1, d + 1)[:, 1:].copy()

def read_fvecs(fname):
  return read_ivecs(fname).view("float32")

def l2_norm(arr):
  l2_norm = np.linalg.norm(arr, axis=1, keepdims=True)
  normalized_array = arr / l2_norm
  return arr

def calculate_average_recall(res, groundtruth):
  top_k = res.shape[1]
  groundtruth_top_k = groundtruth[:, :top_k]
  recalls = [len(set(res[i]).intersection(set(groundtruth_top_k[i]))) / top_k for i in range(res.shape[0])]
  avg_recall = np.mean(recalls)
  return avg_recall


query = l2_norm(read_fvecs("siftsmall/siftsmall_query.fvecs"))
base = l2_norm(read_fvecs("siftsmall/siftsmall_base.fvecs"))
groundtruth = read_ivecs("siftsmall/siftsmall_groundtruth.ivecs")

faiss_index = faiss.IndexHNSWSQ(base.shape[1], faiss.ScalarQuantizer.QT_8bit, M)
faiss_index.hnsw.efConstruction = efConstruction
faiss_index = faiss.IndexIDMap(faiss_index)
faiss_index.train(base)
faiss_index.add_with_ids(base, np.arange(base.shape[0]))

D, I = faiss_index.search(query, k)

avg_recall = calculate_average_recall(I, groundtruth)
print(f"Faiss: {avg_recall}")

table = pa.Table.from_pandas(
  pd.DataFrame({
    'id': np.arange(base.shape[0]).astype(str),
    'embedding': base.tolist()
  }), 
  schema=pa.schema(
    [
      pa.field("id", pa.string()),
      pa.field("embedding", pa.list_(pa.float32(), base.shape[1])),
    ]
  )
)
dataset = lance.write_dataset(
  table, 
  f"/lance_dataset_{str(uuid.uuid4())}", 
  schema=pa.schema(
    [
      pa.field("id", pa.string()),
      pa.field("embedding", pa.list_(pa.float32(), base.shape[1])),
    ]
  ),
  mode="overwrite"
)
dataset.create_index(
  column=["embedding"],
  metric="L2",
  index_type="IVF_HNSW_SQ",
  num_partitions=1,
  max_levelint=12,
  mint=M,
  ef_constructionint=efConstruction,
  replace=True
)
res = np.array([
  dataset.to_table(nearest={"column": "embedding", "q": q, "k": k, "nprobes": 1}).to_pandas().id.to_numpy()
  for q in query
], dtype=int)
avg_recall = calculate_average_recall(res, groundtruth)
print(f"Lance: {avg_recall}")
```

Faiss recall is ~97% in this example whereas Lance is only at ~87%

**Comment by BubbleCal** [comment]
Thanks for feedbacks @zhidongqu-db .
`ef` would significantly impact the recall for HNSW, lance would use `ef = 1.5 * k` by default, which is different from faiss.
You can set `k=100` and `efSearch=150` for faiss.
But we sitll get much lower recall than faiss when `k < 20` with the same `efSearch`, trying to figure it out.
Will make it easy to set `ef` from pylance
