### ISSUE TITLE
bug(python): table update yields unterminated string literal

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#1429]
### What happened?

From discord https://discord.com/channels/1030247538198061086/1258912681168212051

```
For example:
table.update(where=f"id = '{msg.id}'", values={"content": "I'm good, how are you?"})

yields a ValueError: Invalid user input: LanceError(IO): Unterminated string literal. Notably, this doesn't happen for Table.add
```

The schema is

```
pa.schema(
    [
        pa.field("id", pa.string()),
        pa.field("content", pa.string()),
        pa.field("vector", pa.list_(pa.float32(), 384), False),
    ]
)
```

**Comment by wjones127** [comment]
This is most likely due to the fact we are not escaping single quotes when converting the literal values to a SQL string.

Should be an easy fix here:

https://github.com/lancedb/lancedb/blob/fd5ca20f344803c6eddf84c637dd578f488d6a65/python/python/lancedb/util.py#L231
