### ISSUE TITLE
bug(python): error when adding to the database in v0.10

### ISSUE THREAD

**Issue by eduardjbotha** [lancedb/lancedb#1457]
### LanceDB version

v0.10.1 and v0.10.0

### What happened?

I'm using lancedb as the vector database in our RAG app. We have `populate` functionality to ensure that the data in the database is up-to-date. Upon upgrading `lancedb` from `v0.9.0` to `v0.10.1` (also tested with `v0.10.0`), the population fails when adding data to the database.

What I'm using:
 * MacOS Sonoma 14.5
 * python 3.11.7
 * lancedb v0.10.1
 * lancedb.AsyncConnection
 * pydantic 2.8.0 (schema inheriting from lancedb.pydantic.LanceModel)
 * a custom lancedb.embeddings.TextEmbeddingFunction with the lancedb.embeddings.EmbeddingFunctionRegistry

```
table = await db_lance_client.create_table(  # the table gets created successfully
      name=collection_name,
      mode="overwrite",
      schema=get_schema_document().to_arrow_schema(),  # get_schema_document() returns the class inheriting from Lancemodel
)
await table.add(data=data)  # <----- This is where the error occurs
await table.optimize(cleanup_older_than=datetime.timedelta(seconds=1))
await table.create_index(column="processed_text", replace=True)
```

Executing the code with `RUST_BACKTRACE=full` yields this error:
```
[2024-07-19T10:11:37Z WARN  lance::dataset] No existing dataset at /path/to/db_folder/db/db_collection.lance, it will be created
thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-encoding-0.14.1/src/encodings/physical/binary.rs:387:39:
Indices array is empty
stack backtrace:
thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-encoding-0.14.1/src/encodings/physical/binary.rs:387:39:
Indices array is empty
   0:        0x116ed8068 - _PyInit_pyo3_asyncio
   1:        0x115a23d54 - _blake3_compress_in_place_portable
   2:        0x116eb0908 - _PyInit_pyo3_asyncio
   3:        0x116edbd58 - _PyInit_pyo3_asyncio
   4:        0x116edb4fc - _PyInit_pyo3_asyncio
   5:        0x116edd0d8 - _PyInit_pyo3_asyncio
   6:        0x116edc050 - _PyInit_pyo3_asyncio
   7:        0x116edbfb8 - _PyInit_pyo3_asyncio
   8:        0x116edbfac - _PyInit_pyo3_asyncio
   9:        0x116fe9254 - _PyInit_pyo3_asyncio
  10:        0x115a29790 - _blake3_compress_in_place_portable
  11:        0x116fe959c - _PyInit_pyo3_asyncio
  12:        0x1167f8ef0 - _blake3_compress_in_place_portable
  13:        0x1167fca4c - _blake3_compress_in_place_portable
  14:        0x1167fc064 - _blake3_compress_in_place_portable
  15:        0x116ef40b0 - _PyInit_pyo3_asyncio
  16:        0x116efc45c - _PyInit_pyo3_asyncio
  17:        0x116ee7088 - _PyInit_pyo3_asyncio
  18:        0x116ee6d78 - _PyInit_pyo3_asyncio
  19:        0x116edfabc - _PyInit_pyo3_asyncio
  20:        0x19122ef94 - __pthread_joiner_wake
stack backtrace:
   0:    thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-encoding-0.14.1/src/encodings/logical/primitive.rs:421:32:
called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(43), ...)
    0x116ed8068 - _PyInit_pyo3_asyncio
   1:        0x115a23d54 - _blake3_compress_in_place_portable
   2:        0x116eb0908 - _PyInit_pyo3_asyncio
   3:        0x116edbd58 - _PyInit_pyo3_asyncio
   4:        0x116edb4fc - _PyInit_pyo3_asyncio
   5:        0x116edd0d8 - _PyInit_pyo3_asyncio
   6:        0x116edc050 - _PyInit_pyo3_asyncio
   7:        0x116edbfb8 - _PyInit_pyo3_asyncio
   8:        0x116edbfac - _PyInit_pyo3_asyncio
   9:        0x116fe9254 - _PyInit_pyo3_asyncio
  10:        0x115a29790 - _blake3_compress_in_place_portable
  11:        0x116fe959c - _PyInit_pyo3_asyncio
  12:        0x1167f8ef0 - _blake3_compress_in_place_portable
  13:        0x1167fca4c - _blake3_compress_in_place_portable
  14:        0x1167fc064 - _blake3_compress_in_place_portable
  15:        0x116ef40b0 - _PyInit_pyo3_asyncio
  16:        0x116efc188 - _PyInit_pyo3_asyncio
  17:        0x116ee7088 - _PyInit_pyo3_asyncio
  18:        0x116ee6d78 - _PyInit_pyo3_asyncio
  19:        0x116edfabc - _PyInit_pyo3_asyncio
  20:        0x19122ef94 - __pthread_joiner_wake
stack backtrace:
   0:        0x116ed8068 - _PyInit_pyo3_asyncio
   1:        0x115a23d54 - _blake3_compress_in_place_portable
   2:        0x116eb0908 - _PyInit_pyo3_asyncio
   3:        0x116edbd58 - _PyInit_pyo3_asyncio
   4:        0x116edb4fc - _PyInit_pyo3_asyncio
   5:        0x116edd0d8 - _PyInit_pyo3_asyncio
   6:        0x116edc050 - _PyInit_pyo3_asyncio
   7:        0x116edbfb8 - _PyInit_pyo3_asyncio
   8:        0x116edbfac - _PyInit_pyo3_asyncio
   9:        0x116fe9254 - _PyInit_pyo3_asyncio
  10:        0x116fe9564 - _PyInit_pyo3_asyncio
  11:        0x1167fbb48 - _blake3_compress_in_place_portable
  12:        0x116621780 - _blake3_compress_in_place_portable
  13:        0x11662613c - _blake3_compress_in_place_portable
  14:        0x1166251b0 - _blake3_compress_in_place_portable
  15:        0x116afc864 - _blake3_compress_in_place_portable
  16:        0x116afabf0 - _blake3_compress_in_place_portable
  17:        0x116b56bb4 - _blake3_compress_in_place_portable
  18:        0x116b4d8a0 - _blake3_compress_in_place_portable
  19:        0x116b4c7b4 - _blake3_compress_in_place_portable
  20:        0x11511f28c - <unknown>
  21:        0x1151e1614 - <unknown>
  22:        0x115189b9c - <unknown>
  23:        0x116ef4184 - _PyInit_pyo3_asyncio
  24:        0x116efc45c - _PyInit_pyo3_asyncio
  25:        0x116ee7088 - _PyInit_pyo3_asyncio
  26:        0x116ee6d78 - _PyInit_pyo3_asyncio
  27:        0x116edfabc - _PyInit_pyo3_asyncio
  28:        0x19122ef94 - __pthread_joiner_wake
```

I've tried to reproduce the failure with a fairly simple python script, but couldn't manage a successful reproduction in the simple script. I'll try figure out at what complexity it starts producing this error. Hopefully the provided backtrace is enough for you to find the root of the problem.

Please let me know if I should provide any additional information.

**Comment by westonpace** [comment]
This error is coming from the new v2 reader which is still experimental.  We made a breaking change to it between version 0.9 and 0.10.  Is it possible you set `use_legacy_format=False` when you created the original dataset?

There's not a great fix.  If it's easy for you to recreate your dataset then that might be the best approach.  If not, I can investigate what it would take to add in backwards compatibility for that change.

**Comment by eduardjbotha** [comment]
Thanks for the reply. I tried it with `use_legacy_format=False`, but that produced the same error message. With `use_legacy_format=True`, however, it worked. 

There are 2 points:
Point 1)
The code documentation for `use_legacy_format` states that the default value is `True`
```
        use_legacy_format: bool, optional, default True
            If True, use the legacy format for the table. If False, use the new format.
            The default is True while the new format is in beta.
```
but it's actually `None`
```
use_legacy_format: Optional[bool] = None,
```
The default behaviour seems to be the same as `use_legacy_format=False`, not `use_legacy_format=True`.
I suspect it's because the rust code only does something if a value exists (in lancedb/python/src/connection.rs:
```
    if let Some(use_legacy_format) = use_legacy_format {
            builder = builder.use_legacy_format(use_legacy_format);
        }
```


Point 2)
Could the documentation be updated to state that a breaking change was introduced? My first reaction, after discovering a new version was released, is to view the [release information](https://github.com/lancedb/lancedb/releases) for new features and breaking changes. Nothing critical was mentioned in the `v0.10.0` and `v0.10.1` release notes.

**Comment by westonpace** [comment]
You're right, this is a bug when creating tables without initial data, and a pretty serious one.  I've created https://github.com/lancedb/lancedb/pull/1469 with a fix and will get a release out today.

> but it's actually None

The underlying behavior is `True`.

> I suspect it's because the rust code only does something if a value exists

That part is ok (`builder` defaults to `use_legacy_format=false`).  Unfortunately, when creating a table with no data, we don't actually set the format of the table.  It gets set later, once data is first added, and that happens during the `add` call which is regrettably defaulting `use_legacy_format` to `false`.

> Could the documentation be updated to state that a breaking change was introduced? 

This was a major bug, not an intentional change.

**Comment by westonpace** [comment]
Version 0.10.2 is publishing and contains the fix.  Creating an empty table will not use the v2 format unless specified.  Let me know if you are seeing otherwise.

**Comment by eduardjbotha** [comment]
Thank for you for the fix. Here's a summary of things I've noticed with `v0.10.2`:
* creating a table without specifying `use_legacy_format` and then adding works as expected.
* opening a table that was created with `v0.9.0` raises an error. (luckily we refresh/overwrite the values often, so it doesn't affect my situation greatly.
* creating a table while specifying `use_legacy_format=False` raises an error.

`v0.10.2` fixes the bug sufficiently, so I'm going to close this issue. Maybe you find the abovementioned summary useful.
Thanks for quick response. Keep up the good work!
