### ISSUE TITLE
Feature: expose optimize_indices method in both Python and Node APIs

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#1463]
### SDK

Python, Node

### Description

The API to incrementally update indices is missing for Python sync API, and possibly others. This makes it hard to keep indices up-to-date.

We also don't have a user guide discussing this. We should demonstrate how to incrementally update indices, and when users should do that versus full re-indexing.

https://lancedb.github.io/lance/api/python/lance.html#lance.dataset.DatasetOptimizer.optimize_indices

And add docs to use this functionality.

**Comment by universalmind303** [comment]
we do have `table.optimize()` which optimizes [**everything**.](https://github.com/lancedb/lancedb/blob/main/nodejs/lancedb/table.ts#L376). 

instead of exposing a new method, what if we exposed some options on there to only optimize the indices, skipping compaction and pruning

**Comment by QianZhu** [comment]
we have added optimize_indices to python and node
