### ISSUE TITLE
bug(python): LanceError(Index): KMeans: can not train 256 centroids with 100 vectors, choose a smaller K (< 100) instead, but changing k_value to less than 100 does not resolve this

### ISSUE THREAD

**Issue by sungkim11** [lancedb/lancedb#1465]
### LanceDB version

v0.10.1

### What happened?

1. I get an error - LanceError(Index): KMeans: can not train 256 centroids with 100 vectors, choose a smaller K (< 100) instead
2. Change the k_value (i.e., num_partitions) to 1
3. I still get same error.

**Comment by albertlockett** [comment]
Hey @sungkim11! If you only have 100 vectors in your dataset, you probably will not need an index. Flat search should still have good performance. In fact, up to ~10,000 vectors, flat scan performance is usually comparable to or better than search using an index. I would suggest that you can forego creating an index until your table has more rows.

The reason you're still seeing this error even after you've changed `num_partitions` to 1 is that Lance tries to use 8 bits for to represent Product Quantization codes IVF-PQ index. e.g. we try to train 2^8 = 256 centroids for each sub-vector for PQ. The code path for which you're seeing this error is where it is it computing the centroids for PQ, not IVF, and that is why changing `num_partitions` does not resolve the issue. It also means that building an index on < 256 rows doesn't really work. I'll correct the error message to make this more clear.
