### ISSUE TITLE
bug(node): LanceError(IO): file size is too small

### ISSUE THREAD

**Issue by ahaapple** [lancedb/lancedb#1491]
### LanceDB version

0.5.2  @lancedb/lancedb

### What happened?

Error: Failed to add batches to table 5bce1d6f-8bdd-4064-b10c-55bf973701c1: lance error: LanceError(IO): file size is too small, /home/build_user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.12.1/src/utils.rs:86:68

### Are there known steps to reproduce?

```
export async function append(tableName: string, data: lancedb.Data) {
  const db = await getConnection();
  const table = await getTable(db, tableName);
  await table.add(data);
  return table;
}
```

**Comment by wjones127** [comment]
Hello, this looks like a bug when trying to read a corrupted table. Is this for the same use case as https://github.com/lancedb/lancedb/issues/1497 ? I wonder if there is the same underlying issue as there.

**Comment by ahaapple** [comment]
Yes.

These strange errors occurred after a concurrent data import. I suspect it is related to the concurrency of delete, add, and compact. Before the introduction of delete deduplication, I did not encounter these strange errors.

**Comment by ahaapple** [comment]
I will close this issue first, and if version 0.8.0 appears, I will reopen it.

Thanks.

**Comment by BubbleCal** [comment]
Reopen it for now

**Comment by BubbleCal** [comment]
@dhruv2601 how do you reproduce this?
