### ISSUE TITLE
bug(python): optimize_indices cannot be called on vector index with cosine distance type

### ISSUE THREAD

**Issue by alexkohler** [lancedb/lancedb#1492]
### LanceDB version

0.8.1

### What happened?

I'm trying to call `optimize_indices` on a dataset that has a vector index with `cosine` metric/distance type. 

I'm hitting the following error:
```
KMeans::compute_partition: distance type cosine is not supported
```

From what I can tell, `compute_partition` doesn't actually seem to support a `cosine` distance type:
https://github.com/lancedb/lance/blob/526cdd186b0f2fcb840477ac7bfb6f359c5137d7/rust/lance-linalg/src/kmeans.rs#L692-L712

**Comment by wjones127** [comment]
This is fixed by https://github.com/lancedb/lance/pull/2698, which is part of the latest release of lance [^1]. It will be included in the next release of LanceDB.

[^1]: https://github.com/lancedb/lancedb/releases
