### ISSUE TITLE
bug(node): LanceError(Arrow): Invalid argument error: Last offset 102 of Utf8 is larger than values length 51

### ISSUE THREAD

**Issue by ahaapple** [lancedb/lancedb#1497]
### LanceDB version

0.5.2 @lancedb/lancedb

### What happened?

```
Failed to get next batch from stream: lance error: LanceError(IO): Execution error: External error: Execution error: LanceError(Arrow): Invalid argument error: Last offset 102 of Utf8 is larger than values length 51, /home/build_user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.12.1/src/encodings/binary.rs:387:26, /home/build_user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.12.1/src/dataset/scanner.rs:1487:83

Filter
```

### Are there known steps to reproduce?

```
export async function search(query: string, table: string) {
  const db = await getConnection();
  const tbl = await db.openTable(table);

  console.time("embedding");
  const query_embedding = await getEmbedding().embedQuery(query);
  console.timeEnd("embedding");

  console.time("search");
  const results = await tbl
    .vectorSearch(query_embedding)
    .select(["title", "text", "url", "image"])
    .distanceType("cosine")
    .limit(10)
    .toArray();
  console.timeEnd("search");
  return results;
}
```

**Comment by ahaapple** [comment]
```
Failed to get next batch from stream: lance error: LanceError(IO): Execution error: External error: Execution error: LanceError(Arrow): Invalid argument error: Last offset 816 of Utf8 is larger than values length 642, /home/build_user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.12.1/src/encodings/binary.rs:387:26, /home/build_user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.12.1/src/dataset/scanner.rs:1487:83
```

Is this problem related to concurrent reading and writing? How can I avoid this error?  Thanks

**Comment by ahaapple** [comment]
I found out that this is a persistent error, when I try to compact the table I get this error

```
error: lance error: LanceError(IO): Execution error: Row ids did not arrive in sorted order: integers are ordered up to the 0th element, /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-datafusion-0.15.0/src/chunker.rs:47:46
 code: "GenericFailure"
```

I have upgraded to the latest version 0.8.0.

**Comment by wjones127** [comment]
> Is this problem related to concurrent reading and writing?

This has to do with one of your columns having some sort of invalid values. `Last offset 816 of Utf8 is larger than values length 642` is something that would indicate a string column is broken.

What would be most helpful is knowing how you wrote the table. Something must be getting corrupted at that point. It looks like you have an image column (binary?) and a text column (string?).

**Comment by ahaapple** [comment]
Thank you very much for your reply.

https://github.com/memfreeme/memfree/blob/main/vector/db.ts#L14  This is my Schema.


So do I need to perform a Utf8 validation check on each Utf8 column? If there is a problem with this column of data, why is it written successfully?

**Comment by wjones127** [comment]
> So do I need to perform a Utf8 validation check on each Utf8 column? If there is a problem with this column of data, why is it written successfully?

I'm not sure. That may be a bug.

> ```ts
>   new Field("image", new Utf8(), true),
>   new Field("text", new Utf8(), true),
> ```

Are any of these fields very large? like might the columns be `> 2GB`? You might consider instead using `LargeUtf8()`, which might fix the issue.

Otherwise, I think we'd need to come up with a reproducible example so that we can find the source of the bug.

**Comment by ahaapple** [comment]
> Are any of these fields very large? like might the columns be > 2GB? You might consider instead using LargeUtf8(), which might fix the issue.

It should not be larger than 2G, because I used @langchain/textsplitters to split each text

```
const splitter = RecursiveCharacterTextSplitter.fromLanguage("markdown", {
chunkSize: 400,
chunkOverlap: 20,
});
```

> Otherwise, I think we'd need to come up with a reproducible example so that we can find the source of the bug.

I upgraded to 0.8.0 yesterday, and I will try to reproduce it again today.

**Comment by ahaapple** [comment]
0.8.0 should fix this issue
