### ISSUE TITLE
update method support arrays of float for vector column update

### ISSUE THREAD

**Issue by wpjgit** [lancedb/lancedb#1501]
### LanceDB version

v0.11.0

### What happened?

update method support arrays of float for vector column update

### Are there known steps to reproduce?

use dataset: https://github.com/cwida/duckdb-data/releases/download/v1.0/lineitemsf1.snappy.parquet
data convert lance
And after：
    ```

    db = lancedb.connect(uri)
    table = db.open_table(name=name)

    data = [{'_id': '<dbpedia:Joy_of_Life>',
             'title': "Joy of Life update before",
             'text': "Fan Xian is born in the ancient ...",
             'openai': [0.02147006, -0.022711258, 0.011349027, -0.014392599, -0.030396113, ...]}]
    table.add(data)

    data = {'openai': [-0.005945034, -0.045402076, 0.009418799, -0.03202658, -0.017785143, 0.0089392, ...]}
    table.update('_id="<dbpedia:Joy_of_Life>"', data)
```
but error to execute：
Traceback (most recent call last):
  File "/opt/software/lancedb/benchmark_wpj/update_data_v1_1M.py", line 512, in <module>
    update('/opt/dii/lance', 'dbpedia-entities-openai-1M', '_id="<dbpedia:Joy_of_Life>"', data)
  File "/opt/software/lancedb/benchmark_wpj/update_data_v1_1M.py", line 483, in update
    table.update(where, values)
  File "/root/miniconda3/envs/lancedb_benchmark/lib/python3.10/site-packages/lancedb/table.py", line 1650, in update
    self._dataset_mut.update(values_sql, where)
  File "/root/miniconda3/envs/lancedb_benchmark/lib/python3.10/site-packages/lance/dataset.py", line 1053, in update
    self._ds.update(updates, where)
ValueError: Invalid user input: LanceError(IO): Only arrays of literals are supported in lance., /home/runner/work/lance/lance/rust/lance-datafusion/src/planner.rs:535:29, /home/runner/work/lance/lance/rust/lance/src/dataset/write/update.rs:115:14
 
![image](https://github.com/user-attachments/assets/6663223c-4d51-4854-a8c9-ba5fe75d0f74)

**Comment by wjones127** [comment]
Could you share the schema of your table?

```python
table.schema
```

And the exact type that you are inserting?

```python
x = [{"x": [0.1, 0.2]}]
type(data['openai'])
type(data['openai'][0])
```

**Comment by wjones127** [comment]
This very example (updating a vector column) is in the docs here: https://lancedb.github.io/lancedb/python/saas-python/#lancedb.remote.table.RemoteTable.update

So it is definitely supported.

**Comment by wpjgit** [comment]
I used the example you said, the code in the documentation works, but when I change the values to [0.016946921, -0.024341695] it doesn't work

>>> table.update(where='x=2', values={"vector": [0.123,0.987]})
>>> table.to_pandas()
   x          vector
0  1      [1.0, 2.0]
1  3      [5.0, 6.0]
2  2  [0.123, 0.987]
>>> 
>>> 
>>> table.update(where='x=2', values={"vector": [0.016946921, -0.024341695]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/lancedb_benchmark/lib/python3.10/site-packages/lancedb/table.py", line 1650, in update
    self._dataset_mut.update(values_sql, where)
  File "/root/miniconda3/envs/lancedb_benchmark/lib/python3.10/site-packages/lance/dataset.py", line 1053, in update
    self._ds.update(updates, where)
ValueError: Invalid user input: LanceError(IO): Only arrays of literals are supported in lance., /home/runner/work/lance/lance/rust/lance-datafusion/src/planner.rs:535:29, /home/runner/work/lance/lance/rust/lance/src/dataset/write/update.rs:115:14

**Comment by wjones127** [comment]
Hmm, does it work only if there are positive values?

**Comment by wjones127** [comment]
Indeed, I think that's the problem. We can't update vectors if there are negative values 🤦 .

**Comment by wjones127** [comment]
I've made an issue upstream, where this needs to be fixed.

https://github.com/lancedb/lance/issues/2695

**Comment by wpjgit** [comment]
thank you. I understand.
