### ISSUE TITLE
bug(node): Failed to delete rows

### ISSUE THREAD

**Issue by ahaapple** [lancedb/lancedb#1504]
### LanceDB version

0.8.0 @lancedb/lancedb

### What happened?

```
Error: Failed to delete rows in table xxxx: predicate=lance error: Commit conflict for version 924: There was a concurrent commit that conflicts with this one and it cannot be automatically resolved. Please rerun the operation off the latest version of the table.
 Transaction: Transaction { read_version: 922, uuid: "7dcd631a-9058-4921-876c-872021d45b96", operation: Delete { updated_fragments: [Fragment { id: 720, files: [DataFile { path: "537c8e01-b988-41e8-a958-bb7337136830.lance", fields: [0, 1, 2, 3, 4, 5], column_indices: [], file_major_version: 0, file_minor_version: 0 }], deletion_file: Some(DeletionFile { read_version: 922, id: 3554708678589275023, file_type: Array, num_deleted_rows: Some(523) }), row_id_meta: None, physical_rows: Some(21432) }], deleted_fragment_ids: [], predicate: "url == \"https://edu.aliyun.com/course/477/lesson/list?utm_content=m_43084\"" }, tag: None }
 Conflicting Transaction: Some(Transaction { read_version: 922, uuid: "fe5fdd74-3576-427a-85f4-fe63a233969e", operation: Delete { updated_fragments: [Fragment { id: 720, files: [DataFile { path: "537c8e01-b988-41e8-a958-bb7337136830.lance", fields: [0, 1, 2, 3, 4, 5], column_indices: [], file_major_version: 0, file_minor_version: 0 }], deletion_file: Some(DeletionFile { read_version: 922, id: 15097779152250790653, file_type: Array, num_deleted_rows: Some(901) }), row_id_meta: None, physical_rows: Some(21432) }], deleted_fragment_ids: [], predicate: "url == \"https://github.com/heathermiller/dist-prog-book\"" }, tag: None }), /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.15.0/src/io/commit.rs:108:23
```

### Are there known steps to reproduce?

Allow delete and add operations to run concurrently

```
export async function deleteUrl(tableName: string, url: string) {
  const db = await getConnection();
  await retryAsync(async () => {
    const table = await getTable(db, tableName);
    await table.delete(`url == "${url}"`);
  });
  console.log("url", url, "already exists for user", tableName, "deleted");
}


export async function append(tableName: string, data: lancedb.Data) {
  const db = await getConnection();
  const table = await getTable(db, tableName);
  await table.add(data);
  return table;
}
```

**Comment by ahaapple** [comment]
Thanks. I see. But I feel this limitation is a bit big, because it almost means that my vector write service cannot be concurrent and auto-scaling.

**Comment by ahaapple** [comment]
In a multi-process environment, I think it is almost impossible for users to ensure that delete is serial.

**Comment by wjones127** [comment]
If you want to make those deletes work in a multi-process environment, I would add a table-level distributed lock. You can then lock the table before performing the delete operation, ensuring only one delete happens at a time. Note that you can have appends still happen at the same time, as they will not conflict with delete or update operations.

Another option is to always retry when a delete hits a commit conflict with another delete. If you are only occasionally getting this error, this might be the easiest solution.

LanceDB is designs for high concurrency multiprocess reads, but not writes. We use a combination of multi-version concurrency control (MVCC) and optimistic concurrency controls (OCC) to avoid locks on the database, making writes much simpler. This allows concurrent appends, but concurrent updates and deletes are not easy to implement this way. If two update or delete queries modify the same data files, only one of them can be committed to the database.

**Comment by ahaapple** [comment]
Thank you for your detailed explanation.

 I already have a retry mechanism. I will optimize it tomorrow:

First, get all the repeated URLs in a batch of requests from redis on the client, then merge them into a delete request, and then let the new append concurrently.
