### ISSUE TITLE
Feature: add synchronous `to_list` method to the Python async API

### ISSUE THREAD

**Issue by kumancev** [lancedb/lancedb#1517]
### SDK

Python

### Description

Because of the difference between the two api (working with asynchronous table and synchronous table) we have to rewrite most of the code, it is not always handy and does not always get the same result.
It would be great to have the same method when working with an asynchronous table when vector_search

**Comment by wjones127** [comment]
The implementation is pretty straightfoward:

https://github.com/lancedb/lancedb/blob/32123713fd5cd2663505c4f3361b1692ab236353/python/python/lancedb/query.py#L295-L303

There is already a `to_arrow` method to call internally:

https://github.com/lancedb/lancedb/blob/32123713fd5cd2663505c4f3361b1692ab236353/python/python/lancedb/query.py#L1167
