### ISSUE TITLE
bug(node): compaction don't merge the samll files into a big file

### ISSUE THREAD

**Issue by ahaapple** [lancedb/lancedb#1526]
### LanceDB version

0.8.0 @lancedb/lancedb

### What happened?

https://github.com/memfreeme/vector-test/tree/main/broken-data

You could see this lance table files, after compaction, the version only have one, but there are so many small files.

### Are there known steps to reproduce?

https://github.com/memfreeme/vector-test/tree/main

1. bun i
2. bun index.ts
3. bun test test/index-jsonl.test.ts (run multi times)

**Comment by wjones127** [comment]
Hi @ahaapple. Only two of those files are part of your table:

```python
import lance
ds = lance.dataset('broken-data')
ds.get_fragments()
```
```
[LanceFileFragment(id=37, data_files=['433f5966-9f26-42d6-9451-2202486567fc.lance']), LanceFileFragment(id=38, data_files=['10490093-7ed3-40e3-b23c-9596b4a175d0.lance'])]
```

The rest must be leftover from old transactions. This isn't exposed in LanceDB node right now, but if you want to delete those, you will need to pass `delete_unverified` to remove those files. This is explained in [these docs](https://lancedb.github.io/lance/api/python/lance.html#lance.LanceDataset.cleanup_old_versions).

```python
# By default, won't cleanup new untracked files (as they might be part of in-progress transaction).
>>> ds.cleanup_old_versions()
CleanupStats { bytes_removed: 0, old_versions: 0 }
# If we specify to delete unverified, it will force them to be cleaned up.
>>> ds.cleanup_old_versions(timedelta(seconds=0), delete_unverified=True)
CleanupStats { bytes_removed: 6115574, old_versions: 0 }
```

I've made an issue to add the `delete_unverified` parameter to the Node SDK. https://github.com/lancedb/lancedb/issues/1527

**Comment by ahaapple** [comment]
OK, Thank you.
