### ISSUE TITLE
Add Polars integration examples

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#153]
https://github.com/lancedb/lance/issues/936#issuecomment-1577135167

If we can, would be nice to show this for Python *and* Node.

**Comment by prrao87** [comment]
Hi, I wanted to understand how exactly Polars integrates with LanceDB -- say I do not want pandas as a dependency -- I could, in theory read data into a Polars DataFrame, dump it to arrow and then convert it to lance, as per your example linked above in the Lance repo. Right now the only way to be able to use Polars is to use arrow as the intermediary. At some point, will LanceDB expose methods to perform I/O directly from a Polars DataFrame, just like we can do in pandas currently?

**Comment by wjones127** [comment]
> perform I/O directly from a Polars DataFrame, just like we can do in pandas currently?

Actually, for Pandas we convert to arrow too (we just do the conversion for you.)

polars is arrow native, so there’s not much overhead. But there are probably UX improvements we could make for sure.
