### ISSUE TITLE
bug(python): Watsonx integration in Embedding API

### ISSUE THREAD

**Issue by PrashantDixit0** [lancedb/lancedb#1535]
### What happened?

While using Watsonx models through Embedding API throwing error
```Status code: 400, body: {"errors":[{"code":"invalid_input_argument","message":"Invalid input argument for Model 'ibm/slate-125m-english-rtrvr': Token sequence length is longer than the specified maximum sequence length for this model (1336 \u003e 512).","more_info":"https://cloud.ibm.com/apidocs/watsonx-ai"}],"trace":"85527f4d559b71672661bd561a6768fe","status_code":400}
WARNING:root:Error occurred: Failure during generate. (POST https://us-south.ml.cloud.ibm.com/ml/v1/text/embeddings?version=2024-07-29)
```

using the same credentials following official documentation of IBM watson, it is working
https://ibm.github.io/watsonx-ai-python-sdk/fm_embeddings.html

### Are there known steps to reproduce?

Using following code for creating table and using embeddings of watson

```
import os
import lancedb
from lancedb.pydantic import LanceModel, Vector
from lancedb.embeddings import EmbeddingFunctionRegistry

watsonx_embed = EmbeddingFunctionRegistry.get_instance().get("watsonx").create(
    name="ibm/slate-125m-english-rtrvr",
    api_key="API_KEY",
    project_id="PROJECT_ID",
    url = "https://us-south.ml.cloud.ibm.com"
  )
class TextModel(LanceModel):
    text: str = watsonx_embed.SourceField()
    vector: Vector(watsonx_embed.ndims()) = watsonx_embed.VectorField()
```

**Comment by AyushExel** [comment]
Hey @h0rv can you take a look at this one? Thanks!

**Comment by h0rv** [comment]
Hi @PrashantDixit0, are you able to see the error returned from the watsonx.ai API?

**Comment by PrashantDixit0** [comment]
This Error I got while using it with LanceDB Embedding API,
``Error occurred: Failure during generate. (POST https://us-south.ml.cloud.ibm.com/ml/v1/text/embeddings?version=2024-07-29)
``

**Comment by h0rv** [comment]
Is there no other logs? Also, are your watsonx credentials up to date and valid?

**Comment by PrashantDixit0** [comment]
I used the same credentials following the official documentation of IBM Watson, it is working
https://ibm.github.io/watsonx-ai-python-sdk/fm_embeddings.html

There are the main error logs which I got
