### ISSUE TITLE
bug(python): build index very slow

### ISSUE THREAD

**Issue by oswardlx** [lancedb/lancedb#1549]
### What happened?

there is my code
`import lancedb
conn = lancedb.connect('../app_data2/test1')
tb = conn.open_table('testTablePre2')
tb.create_index(num_partitions=3200, num_sub_vectors=1024,vector_column_name = 'embedding',accelerator='cuda')

print(tb.count_rows())`

and there is my log

 58%|█████▊    | 29/50 [06:06<04:25, 12.64s/it]  
  0%|          | 0/49930500 [00:00<?, ?it/s]/home/admin/.conda/envs/lancedb2/lib/python3.10/site-packages/lance/torch/data.py:65: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
  tensor = torch.from_numpy(arr.to_numpy(zero_copy_only=False))
100%|██████████| 49930500/49930500 [13:49<00:00, 60213.17it/s] 
49930500

i got Fifty million vector
and 
The following two lines of logs have been directly processed for 8-9 hours：

100%|██████████| 49930500/49930500 [13:49<00:00, 60213.17it/s] 
--------8-9 hours
49930500

How to build  index faster？

**Comment by wjones127** [comment]
What's the dimension of your vectors? Setting `num_sub_vectors=1024` might be too high.

**Comment by oswardlx** [comment]
> 你的向量维数是多少？设置`num_sub_vectors=1024`可能太高了。

My vector dimension is 1024

**Comment by oswardlx** [comment]
> What's the dimension of your vectors? Setting `num_sub_vectors=1024` might be too high.

My vector dimension is 1024

**Comment by eddyxu** [comment]
Could you also share the machine configuration @oswardlx ?
i.e. How many CPU cores, local disk size, use GPU?

**Comment by oswardlx** [comment]
128 core
1T memory
7 GeForce RTX 4090

tb.create_index(num_partitions=3200, num_sub_vectors=1024,vector_column_name = 'embedding',accelerator='cuda')

**Comment by oswardlx** [comment]
> Could you also share the machine configuration @oswardlx ? i.e. How many CPU cores, local disk size, use GPU?

2T disk
