### ISSUE TITLE
bug(python): Attribute "rerank" is unknown

### ISSUE THREAD

**Issue by sayandipdutta** [lancedb/lancedb#1550]
### LanceDB version

v0.12.0

### What happened?

Attempting to use `.rerank` method on `table.search` results generates `reportAttributeAccessIssue` in `pyright` and `pylance`.
```python
assert isinstance(table, LanceTable)
result3 = (
    table.search(query, query_type="hybrid")
    .where(criterion, prefilter=True)
    .limit(5)
    .rerank(reranker=reranker)  # <- Attribute "rerank" is unknown
)
```
![image](https://github.com/user-attachments/assets/88e4fbd9-47ef-4f03-a7a0-0342cb354660)

### Expected:
Should not issue type checker error.

### Are there known steps to reproduce?
Create a LanceTable instance, and try to perform reranking on a search result.

```python
import lancedb  # type: ignore[import-untyped]
from lancedb.embeddings import get_registry  # type: ignore[import-untyped]
from lancedb.pydantic import LanceModel, Vector  # type: ignore[import-untyped]
from lancedb.rerankers import LinearCombinationReranker  # type: ignore[import-untyped]

model_registry = get_registry().get("sentence-transformers")
model = model_registry.create(name="BAAI/bge-small-en-v1.5")

class Document(LanceModel):
    text: str = model.SourceField()
    vector: Vector(model.ndims()) = model.VectorField()

db = lancedb.connect(".test_db")
assert isinstance(db, lancedb.LanceDBConnection)
table = db.create_table("test_table", schema=Document, exist_ok=True)
table.create_fts_index("text")

reranker = LinearCombinationReranker(weight=0.3, return_score="all")

result = (
    table.search("foo", query_type="hybrid")
    .where("category = 'bar'", prefilter=True)
    .limit(5)
    .rerank(reranker=reranker)
)
```

---

This happens because `LanceTable.search` returns a `LanceQueryBuilder`. It should dispatch different types of query builders based on `query_type` parameter. Adding a few overloads on `LanceTable.search` based on `Literal` query types should solve the issue.

**Comment by sayandipdutta** [comment]
If this is intended to be fixed, I would be glad to do the work.

**Comment by AyushExel** [comment]
Sure feel free to send us a PR. If not, I can try to get to this sometime after next week.

**Comment by sayandipdutta** [comment]
I'll send a PR tomorrow
