### ISSUE TITLE
Feature: expose `offset` in query APIs

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#1555]
### SDK

Python, TypeScript, Rust

### Description

Support a version of pagination where users can provide `offset` in addition to `limit`. The underlying Lance APIs support this, so it shouldn't be hard to implement.

The `explain_plan` PR is a good model for how to wire up a LanceDB query API to an existing Lance feature: https://github.com/lancedb/lancedb/commit/46c6ff889d37733c277f3b40d95c317af30f1c8b

* [x] Rust
* [x] Python
* [ ] Typescript

**Comment by kartik-raj7** [comment]
Can you assign me this issue

**Comment by wjones127** [comment]
@kartik-raj7 I think someone else has already started this  https://github.com/lancedb/lancedb/pull/1556
