### ISSUE TITLE
bug(python): Filtering without Vector Search does not work on LanceDB Cloud

### ISSUE THREAD

**Issue by tleyden** [lancedb/lancedb#1566]
### LanceDB version

LanceDB Cloud

### What happened?

The [docs](https://lancedb.github.io/lancedb/sql/#filtering-without-vector-search) mention that:

> You can also filter your data without search.

```
tbl.search().where("id = 10").limit(10).to_arrow()
```

However when I try it on lancedb cloud:

```
db = lancedb.connect(
  uri="db://..",
  api_key="...",
  region="us-east-1"
)
tbl_opened = db.open_table(table_name)
result = (
    tbl_opened.search()
    .where("file_path = 'foo.txt'", prefilter=True)
    .limit(100)
    .to_arrow()
)
```

I get an error:

```
TypeError: RemoteTable.search() missing 1 required positional argument: 'query'
```

### Are there known steps to reproduce?

See above

**Comment by BubbleCal** [comment]
fixed by https://github.com/lancedb/lancedb/pull/1698
