### ISSUE TITLE
bug(python): OSError: LanceError(IO): Generic LocalFileSystem error, Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by HamzaFarhan** [lancedb/lancedb#1630]
### LanceDB version

v0.13.0

### What happened?

I'm getting this error when creating a LanceDB table in an attached Volume in my Modal app.

OSError: LanceError(IO): Generic LocalFileSystem error: Unable to copy file from /home/hamza/dev/lance/index3/application-security-standards.lance/_versions/.tmp_1.manifest_d9d1ab1d-273a-4c40-b217-dc2a820261b4 to /home/hamza/dev/lance/index3/application-security-standards.lance/_versions/1.manifest: Operation not permitted (os error 1), /home/runner/work/lance/lance/rust/lance-table/src/io/commit.rs:693:54

**Comment by wjones127** [comment]
It sounds like you are using a filesystem that doesn't support hard link. That is required for LanceDB to function. You should either mount a fully-featured filesystem, or connect to an object storage service.
