### ISSUE TITLE
bug(python): ColBERTReranker does not accept "device" param

### ISSUE THREAD

**Issue by marketneutral** [lancedb/lancedb#1641]
### LanceDB version

v0.13.0

### What happened?

The [docs for ColBERTReranker](https://lancedb.github.io/lancedb/reranking/colbert/) say that an accepted parameter is the `device`, but this is not actually suported in the [code](https://github.com/lancedb/lancedb/blob/bf7d2d6fb048b2105d3f3ff7016765161c8fff79/python/python/lancedb/rerankers/colbert.py#L17).

I am trying to set the device to CPU, but it is automatically going to GPU.

**Comment by AyushExel** [comment]
Yup thats a bug. Probably got introduced when shifting it from HF to rerankers implementation. Will fix this tmrw
