### ISSUE TITLE
Feature: Rust remote client configuration

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#1642]
### SDK

Rust

### Description

For the Rust SDK remote API, should be able to configure:

* Table cache
* Request timeouts

**Comment by judahrand** [comment]
> Table cache

This would be amazing - especially for the use case when a specific table version is checked out and so it is known that the data will not change.

**Comment by wjones127** [comment]
Closed by https://github.com/lancedb/lancedb/issues/1642

**Comment by judahrand** [comment]
> Closed by #1642

Did you mean #1639?

**Comment by wjones127** [comment]
Sorry I meant https://github.com/lancedb/lancedb/pull/1696

This is also a duplicate of https://github.com/lancedb/lancedb/issues/1684
