### ISSUE TITLE
bug(python): Hybrid search syntax broken?

### ISSUE THREAD

**Issue by logan-markewich** [lancedb/lancedb#1652]
### LanceDB version

v0.13.0

### What happened?

I'm trying to update the integration in the [llama-index](https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/vector_stores/llama-index-vector-stores-lancedb) repo

Currently, unit tests for the hybrid search are failing. It seems like support for passing in both the query text and vector was removed/changed ? And If I use the following syntax from the docs

```
vector_query = [0.1, 0.2, 0.3, 0.4, 0.5]
text_query = "flower moon"
results = table.search(query_type="hybrid")
                .vector(vector_query)
                .text(text_query)
                .limit(5)
                .to_pandas()
```

I get a not-implemented error for `.vector(vector_query)`

Any help would be appreciated!

### Are there known steps to reproduce?

Run unit tests for the llama-index integration

**Comment by AyushExel** [comment]
Hi @logan-markewich, yes we've updated the hybrid search api with a breaking change. Limiting version should be good for now. I'll update llama-index integration and send you guys a PR this week!

**Comment by AyushExel** [comment]
@logan-markewich https://github.com/run-llama/llama_index/pull/16057/
