### ISSUE TITLE
bug(python): i can't connect other oss server

### ISSUE THREAD

**Issue by oswardlx** [lancedb/lancedb#1668]
### LanceDB version

0.12.0

### What happened?

i want to connect db and overwrite Object Storage by myself
but i can't find where to implement like s3
what should i do

**Comment by AyushExel** [comment]
Have you tried our cloud storage guide https://lancedb.github.io/lancedb/guides/storage/ ?

**Comment by oswardlx** [comment]
> Have you tried our cloud storage guide https://lancedb.github.io/lancedb/guides/storage/ ?

my Obejct Storage is not in (AWS S3,Google Cloud Storage,Azure Blob Storage) 
Can I customize the relevant read and write operations and then connect to other cloud storage？

**Comment by wjones127** [comment]
> Can I customize the relevant read and write operations and then connect to other cloud storage?

We don't currently support implementing custom object store clients.

Does yours have an S3 API? many object stores (including Cloudflare R2, GCS, Minio) have S3-compatible APIs that work with any S3 client.

**Comment by oswardlx** [comment]
thanks

**Comment by oswardlx** [comment]
> > Can I customize the relevant read and write operations and then connect to other cloud storage?
> 
> We don't currently support implementing custom object store clients.
> 
> Does yours have an S3 API? many object stores (including Cloudflare R2, GCS, Minio) have S3-compatible APIs that work with any S3 client.

i used S3 API connect my object store ,create table and add data。but i can't find what the data file like.for example:
local file like :file1/table1

i connect S3 like :s3://xxxxxxxxxxxxxx:lancedb/test2/"
and create table:testoss
but i can't find somefile like testoss.lance or anything else like local store lancedb/test2/testoss.lance

**Comment by oswardlx** [comment]
i used boto3.client can connect Obejct Storage. 
 but use lancedb,can't connect it。
 
 Lancedb links S3 with many parameters hidden, exposing a storage _options
But I don't know how it was requested later

**Comment by wjones127** [comment]
> but use lancedb,can't connect it

Could you share the exact errors or failure you are seeing? It's hard to help you without that.

I'd also recommend giving this section of the docs another read: https://lancedb.github.io/lancedb/guides/storage/#s3-compatible-stores

**Comment by oswardlx** [comment]
> > but use lancedb,can't connect it
> 
> Could you share the exact errors or failure you are seeing? It's hard to help you without that.
> 
> I'd also recommend giving this section of the docs another read: https://lancedb.github.io/lancedb/guides/storage/#s3-compatible-stores


when 
url = "s3://{Bucket}/{path}"
endpoint="https://{endpoint}"
response is RuntimeError: lance error: LanceError(IO): Generic S3 error: Error performing list request: Client error with status 403 Forbidden
main message is Please use virtual hosted style to access.

when 
url = "s3://{path}"
endpoint="https://{Bucket}.{endpoint}"
response is RuntimeError: lance error: LanceError(IO): Generic S3 error: Error performing list request: Client error with status 404 Not Found:
main message is The specified key does not exist. 
key is {path}

when
url="s3://bb.txt"
endpoint = "https://{Bucket}.{endpoint}/{path}"
response is : Generic S3 error: Got invalid list response: invalid type: string "erewr", expected struct ListResponse, /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.16.0/src/object_store.rs:579:22

"erewr" is a String in bb.txt
it seems like lancedb can connect my storage,and read file。but there are some protocol issues, I don't know if it's compatibility or configuration issues
my storage_options is {
    "region":"xxxxxx",
    "endpoint":endpoint4,
    "allow_http": "true",
    "access_key_id": access_key_id,
    "secret_access_key": secret_access_key
    }
    
    help me

**Comment by oswardlx** [comment]
i known!!!!!!!
i need to config virtual_hosted_style_request=true in stroage_options!!!!!!!!!!
