### ISSUE TITLE
Feature: Is there a plan to support golang?

### ISSUE THREAD

**Issue by skyleaworlder** [lancedb/lancedb#1669]
### Description

I would like to know if there is a plan to support golang sdk?

**Comment by skyleaworlder** [comment]
> We at LanceDB don’t have any plans to. But if someone wants to contribute go lang bindings they are welcome to.

Thanks for your reply. Feel sad to hear that 😢

**Comment by paulwalsh-sonrai** [comment]
@skyleaworlder Over the weekend, I began developing Golang bindings for LanceDB and pushed a work-in-progress commit: [df466bdf0739ba191fcbe6bd3e0be15926976d0a](https://github.com/paulwalsh-sonrai/lancedb/commit/df466bdf0739ba191fcbe6bd3e0be15926976d0a#diff-c1002c356fc165756b90c977cdbe95fd6cdb80f2ef1cdeeceb0ec07dbb018e43).

My day job uses Lance, and we’re currently in the process of rewriting a LangChain agent in Golang, so we need to interact with Lance files. I've set up a few basic APIs that can be accessed from cgo, including `createConnection`, `createTable`, `countRows`, and a couple of others.

Alternatively, I am considering wrapping Lance's existing Node.js SDK in JavaScript code that pipes function outputs to stdout, which can then be captured by the Go runtime using exec.Command. While this approach is somewhat hacky, it should work adequately until I can create more bindings.

```javascript
async function queryTable() {
  try {
    const rst = await tbl
      .query()
      .limit(2)
      .nearestTo(
        Array(32)
          .fill(1)
          .map(() => Math.random())
      )
      .toArrow();

   // Output `rst` as JSON
    console.log(JSON.stringify(rst));
  } catch (error) {
    console.error("Error:", error);
    process.exit(1);
  }
}

queryTable();


```
the the golang would look something like this 

```golang
package main

import (
    "encoding/json"
    "fmt"
    "os/exec"
    "strings"
)

// Define a struct that matches the JSON structure of `rst`
type Result struct {
    NumRows int `json:"numRows"`
    // Add other fields that `rst` might contain
}

func main() {
    // Execute the Node.js script
    cmd := exec.Command("node", "table_query_wrapper.js")

    // Capture the output
    output, err := cmd.Output()
    if err != nil {
        fmt.Println("Error executing JavaScript:", err)
        return
    }

    // Convert the output to a string
    resultJSON := strings.TrimSpace(string(output))

    // Parse the JSON output
    var result Result
    err = json.Unmarshal([]byte(resultJSON), &result)
    if err != nil {
        fmt.Println("Error parsing JSON:", err)
        return
    }

    // Print the parsed output
    fmt.Printf("Number of rows: %d\n", result.NumRows)
    // Print other fields if needed
}


``

**Comment by yonomitt** [comment]
> [@skyleaworlder](https://github.com/skyleaworlder) Over the weekend, I began developing Golang bindings for LanceDB and pushed a work-in-progress commit: [df466bdf0739ba191fcbe6bd3e0be15926976d0a](https://github.com/paulwalsh-sonrai/lancedb/commit/df466bdf0739ba191fcbe6bd3e0be15926976d0a#diff-c1002c356fc165756b90c977cdbe95fd6cdb80f2ef1cdeeceb0ec07dbb018e43).
> 
> My day job uses Lance, and we’re currently in the process of rewriting a LangChain agent in Golang, so we need to interact with Lance files. I've set up a few basic APIs that can be accessed from cgo, including `createConnection`, `createTable`, `countRows`, and a couple of others.
> 
> Alternatively, I am considering wrapping Lance's existing Node.js SDK in JavaScript code that pipes function outputs to stdout, which can then be captured by the Go runtime using exec.Command. While this approach is somewhat hacky, it should work adequately until I can create more bindings.
> 
> async function queryTable() {
>   try {
>     const rst = await tbl
>       .query()
>       .limit(2)
>       .nearestTo(
>         Array(32)
>           .fill(1)
>           .map(() => Math.random())
>       )
>       .toArrow();
> 
>    // Output `rst` as JSON
>     console.log(JSON.stringify(rst));
>   } catch (error) {
>     console.error("Error:", error);
>     process.exit(1);
>   }
> }
> 
> queryTable();
> the the golang would look something like this
> 
> package main
> 
> import (
>     "encoding/json"
>     "fmt"
>     "os/exec"
>     "strings"
> )
> 
> // Define a struct that matches the JSON structure of `rst`
> type Result struct {
>     NumRows int `json:"numRows"`
>     // Add other fields that `rst` might contain
> }
> 
> func main() {
>     // Execute the Node.js script
>     cmd := exec.Command("node", "table_query_wrapper.js")
> 
>     // Capture the output
>     output, err := cmd.Output()
>     if err != nil {
>         fmt.Println("Error executing JavaScript:", err)
>         return
>     }
> 
>     // Convert the output to a string
>     resultJSON := strings.TrimSpace(string(output))
> 
>     // Parse the JSON output
>     var result Result
>     err = json.Unmarshal([]byte(resultJSON), &result)
>     if err != nil {
>         fmt.Println("Error parsing JSON:", err)
>         return
>     }
> 
>     // Print the parsed output
>     fmt.Printf("Number of rows: %d\n", result.NumRows)
>     // Print other fields if needed
> }
> 
> 
> ``

Hi, I'm looking for Go bindings for LanceDB. What's the state of the project you started? How much effort, do you think it would be for someone to finish it?

**Comment by paulwalsh-1212** [comment]
Hi, i did not get much further as we decided it was not worth it. I would advise to have a good workflow/env for creating and testing the commands, the process of going from  rust sdk -> cgo -> go was quite difficult at the time since i didnt have the proper tools to work in all three runtimes making for a significantly more drawn out experience. 

This is what i have used when i have needed to use golang and vectordb ->  https://github.com/philippgille/chromem-go

Has served me fine so far, but defs not nearly as good as lance.

**Comment by skyleaworlder** [comment]
> Hi, i did not get much further as we decided it was not worth it. I would advise to have a good workflow/env for creating and testing the commands, the process of going from rust sdk -> cgo -> go was quite difficult at the time since i didnt have the proper tools to work in all three runtimes making for a significantly more drawn out experience. If you regular work wiith all 3 runtime is shouldn't be too bad at all.
> 
> This is what i have used when i have needed to use golang and vectordb -> https://github.com/philippgille/chromem-go
> 
> Has served me fine so far, but defs not nearly as good as lance.

Agree. I also chose chromem-go after I found there is no go sdk for lancedb.

But I have to say chromem-go is good, but trading off high memory usage. Finally, I chose sqlite-vec.

**Comment by mdrideout** [comment]
My Opentelemetry ingestion server is GO based, and I use SQLite and DuckDB. LanceDB would be a great addition to the stack.

I also need a low-memory solution that is file based, so chromem-go doesn't quite fit the bill. 

- duckdb has an expiremental vector search extension https://duckdb.org/docs/stable/extensions/vss.html
- as mentioned above sqlite-vec is another option

Would be great to have a native embeddable vector db like LanceDB available in a GO environment. 

Just commenting in case others arrive here from search looking for options, and to add to the voice that this is desired. I would imagine, given how huge GO is in the telemetry scene and low-resource server-scene, that there would be a decent amount of demand.

**Comment by mohamad-tohidi** [comment]
@yonomitt Hello
is the project open source?
how can we discuss the work that you did?

**Comment by mohamad-tohidi** [comment]
wait
what is this then?

https://pkg.go.dev/github.com/lancedb/lancedb-go/pkg/lancedb#hdr-Key_Features
