### ISSUE TITLE
'LanceEmptyQueryBuilder' object has no attribute 'vector'

### ISSUE THREAD

**Issue by jagadeshanh** [lancedb/lancedb#1691]
### Description

```
import lancedb

vector_query = [0.1, 0.2, 0.3, 0.4, 0.5]
text_query = "flower moon"
results = table.search(query_type="hybrid").vector(vector_query).text(text_query).limit(5).to_pandas()

```

Referring to example from documentation https://lancedb.github.io/lancedb/hybrid_search/hybrid_search/#hybrid-search-in-lancedb code fails with error

**'LanceEmptyQueryBuilder' object has no attribute 'vector'**

**Comment by AyushExel** [comment]
can you make sure you're running latest lancedb by updating via `pip install --upgrade lancedb`. Let me know if you still see the error

**Comment by AyushExel** [comment]
Actually there is a different bug that will always ask you to pass `vector_column_name` when passing queries explicitly. I'll fix that

**Comment by jagadeshanh** [comment]
Thanks @AyushExel
