### ISSUE TITLE
Feature: Add Support for Azure OpenAI Embeddings

### ISSUE THREAD

**Issue by marketneutral** [lancedb/lancedb#1699]
### SDK

Python

### Description

Azure provides access to OpenAI and other models, but the `openai` client object is different. I copy/pasted and modified `python/python/lancedb/embeddings/openai.py` to support Azure embeddings.... just change the client object.

https://github.com/lancedb/lancedb/blob/e606a455dfb5d9250f6955f4c0c6102001b15aba/python/python/lancedb/embeddings/openai.py#L118

```diff
-       return openai.OpenAI(**kwargs)
+      return openai.AzureOpenAI(**kwargs)
```
The Azure OpenAI client however needs an additional kwarg for `api_version`. I satisfy this by just setting an environment variable (`OPENAI_API_VERSION="2023-09-01-preview"`), but perhaps you want the user to be able to pass this in.

**Comment by AyushExel** [comment]
ice..We could just subclass this and change the client to AzureOpenAI. We'll prioritise it sometime next month if its not a blocker anymore.
