### ISSUE TITLE
`tbl` doesn't have `to_pandas`

### ISSUE THREAD

**Issue by BBischof** [lancedb/lancedb#17]
Sorry if missing something obvious; cell 6 in this: https://github.com/lancedb/lancedb/blob/f544c5dd31f0cd25483a2848009463546aadb964/notebooks/youtube_transcript_search.ipynb doesn't work for me because tbl is of type `LanceTable`. 

This works (lol):
```
tbl.to_lance().to_table().to_pandas()
```

**Comment by BBischof** [comment]
A minor comment is that the previous cell is grumpy if you clone the repo and run the notebook because the dataset already exists. Might be better to remove the dataset from the repo so clone and run works more smoothly

**Comment by changhiskhan** [comment]
I think I was translating between Lance APIs and this new repo and carried a typo over. Good catch thanks for the issue!

**Comment by changhiskhan** [comment]
Ok just made another release. The missing method was in main but not released. In the notebook I also just added an rm -rf on the dataset directory so there's no conflict.

**Comment by changhiskhan** [comment]
Closing as completed. Thanks again for the feedback!
