### ISSUE TITLE
bug(Java): Is there any handsome or beautiful guy who can provide a solution for Java integration, using Maven instead of JNI

### ISSUE THREAD

**Issue by oswardlx** [lancedb/lancedb#1710]
### What happened?

We need easy-to-use Java packages
Or what methods or steps can generally be used to make Java compatible? I may have time to figure it out

**Comment by wjones127** [comment]
We have native code we need to bind to, so not sure how we can get around JNI.

Is there another project we might be able to use as inspiration? What would be most helpful is to see one that is implemented in Rust.
