### ISSUE TITLE
bug(python): create LabelList.    but list_indices it calls IVFPQ

### ISSUE THREAD

**Issue by oswardlx** [lancedb/lancedb#1711]
### LanceDB version

0.13.0

### What happened?

i create index like:
    await tbl.create_index("tags", config=LabelList())

but when i run :
    config = await tbl.list_indices();
 
 config print :
[Index(**IvfPq,** columns=["tags"])]

Is this a display issue or is the underlying data ivfQp

**Comment by wjones127** [comment]
Thanks for reporting @oswardlx .

This appears to be related to https://github.com/lancedb/lance/issues/2039

I'll look into fixing this.
