### ISSUE TITLE
bug(python): `LanceEmptyQueryBuilder` does not work with `with_row_id`

### ISSUE THREAD

**Issue by MrLoh** [lancedb/lancedb#1724]
### LanceDB version

v0.11.0

### What happened?

When I make an empty query (`search(None)`) to just get back all rows for example. I somehow don't get back the `_row_id` when using the `with_row_id`.

```py
db.open_table("my_table").search().with_row_id(True).limit(1).to_list()
```

### Are there known steps to reproduce?

1. Create a table
2. Insert some data. 
3. Try to select with `db.open_table("my_table").search().with_row_id(True).limit(1).to_list()`
4. Observe missing `_row_id`

**Comment by wjones127** [comment]
This seems to be fixed in the latest version. I've added a unit test for this in: https://github.com/lancedb/lancedb/pull/1835
