### ISSUE TITLE
bug(python): What are the standards for SQL

### ISSUE THREAD

**Issue by oswardlx** [lancedb/lancedb#1733]
### LanceDB version

0.13.0

### What happened?

What are the standards for SQL, MySQL, Oracle, or something else? I want to look up some related operations

**Comment by wjones127** [comment]
The functions available are mostly from DataFusion: https://datafusion.apache.org/user-guide/sql/scalar_functions.html

We don't support full SQL queries yet and haven't committed to a particular standard. We have a few particular customizations which are documented here: https://lancedb.github.io/lancedb/sql/#sql-filters
