### ISSUE TITLE
"use_tantivity" flag does not apply to LanceDB Cloud

### ISSUE THREAD

**Issue by tleyden** [lancedb/lancedb#1755]
### Description

In this code sample:

```
# passing `use_tantivy=False` to use lance FTS index
# `use_tantivy=True` by default
table.create_fts_index("text")
```

and api docs:

```
Help on method create_fts_index in module lancedb.remote.table:

create_fts_index(column: str, *, replace: bool = False, with_position: bool = True) method of lancedb.remote.table.RemoteTable instance
    Create a full-text search index on the table.
    
    Warning - this API is highly experimental and is highly likely to change
    in the future.
    
    Parameters
    ----------
    .........
    use_tantivy: bool, default True
        If True, use the legacy full-text search implementation based on tantivy.
        If False, use the new full-text search implementation based on lance-index.
```

it might be good if the docs mention that `use_tantivity` is not relevant to LanceDB cloud.  When I passed `use_tantivity=False`, I got this error:

```
TypeError: RemoteTable.create_fts_index() got an unexpected keyword argument 'use_tantivy'
```

I'm assuming that means on LanceDB cloud it will default to native FTS?

### Link

https://lancedb.github.io/lancedb/fts/#example

**Comment by BubbleCal** [comment]
Thanks for feedbacks!
Yes `use_tantivity=True` is not supported on LanceDB Cloud, it uses native FTS.
We should doc this FYI @QianZhu

**Comment by tleyden** [comment]
Awesome thanks!  

BTW, it might be a bit easier to understand the docs if you just split them into two separate pages:

* Native FS
* Tantivity

**Comment by BubbleCal** [comment]
BTW could you tell for the native FTS, what features are missing for your use cases?
we are moving to native FTS, so happy to know what is blocking you
