### ISSUE TITLE
Cohere re-ranker example doesn't mention "pip install cohere" is needed

### ISSUE THREAD

**Issue by tleyden** [lancedb/lancedb#1757]
### Description

With this code:

```

from lancedb.rerankers import CohereReranker
cohere_reranker = CohereReranker(column="content")
fts_search_table.search("screenshot", query_type="hybrid").rerank(reranker=cohere_reranker).limit(5).select(["content"]).to_list()
```

I got an error: `you must install cohere`

After doing a `pip install cohere` it worked (yay!) but it would've been helpful if the docs had mentioned it.

### Link

https://lancedb.github.io/lancedb/reranking/cohere/

**Comment by QianZhu** [comment]
Thanks for the feedback @tleyden ! Docs updated!
