### ISSUE TITLE
bug(python): Tantivy FTS uses wrong row id to build index

### ISSUE THREAD

**Issue by jonas768** [lancedb/lancedb#1759]
### LanceDB version

v0.14.0

### What happened?

I have been using LanceDB quite a while and am a little bit at loss how to find the cause for the issue I am having.

I have a large amount of data with precomputed embeddings. I add these directly in full from a polar dataframe like so:

table = lance_db.create_table("TestTable", data=polar_df, mode='overwrite')

then i create my Fulltext-Index
table.create_fts_index("chunk_text", replace=True)

Then i do my hybrid query like so:
reranker = (LinearCombinationReranker(weight=vector_weight, return_score="all") 
results = table.search(query_type="hybrid").vector(query_embedding).text(preprocessed_query).limit(limit).rerank(reranker=reranker, normalize="score").with_row_id(True).to_polars()

Now in the result dataset i have duplicates. It seems the row_ids differ between the vector search results (these are often way off and very high) and the full-text search results (these correspond almost to the number of rows of my polar dataframe)

I then get the exact same chunk_id sometimes twice in my merged results. So the linear combination reranker could not merge the scores because of the different row_id.

Example in the screenshot. Exact same row. Vector_ID is way off and thus vector result appears in one row and the full-text result with the more resenable id appears below. -> Both have their individual relevance score.

![Screenshot 2024-10-17 214036](https://github.com/user-attachments/assets/00e59529-461b-4848-99a1-eda5dc126930)

For context:
Table has ~1.6 million rows
row_ids for full-text-search range from 0 to 1.6 million (as expected!)
row_ids for vector results are all over the place.

I tried:
Adding data in batches of 1000 or 100.000. The smaller the batches the higher the sphere of the vector row_ids.
When adding all 1.6million rows in a single step vector_ids seem fine up to around one million then there is a big jump.
When adding first just 1 million rows and the rest in batches of 100.000 row_ids for vector search are still way off after around a million:

Newly created table (from polar_df), first with million records, then rest in batches of 100.000
![image](https://github.com/user-attachments/assets/61a7fa9d-757b-48aa-86cd-7bab4652bf87)

No difference between adding polar or pyarrow.

Help would be appreciated!

### Are there known steps to reproduce?

table = lance_db.create_table("TestTable", data=polar_df, mode='overwrite')

then i create my Fulltext-Index
table.create_fts_index("chunk_text", replace=True)

Then i do my hybrid query like so. Here i typically see duplicate chunk_ids (my unique id) so the same row from a polars dataframe gets a different id when using vector search then for the full-text search. During Merge these results get concatenated and thus the duplicates (with wrong reranking relevance scores and always either distance or text-score missing in case of linear combination reranker)

reranker = (LinearCombinationReranker(weight=vector_weight, return_score="all") 
results = table.search(query_type="hybrid").vector(query_embedding).text(preprocessed_query).limit(limit).rerank(reranker=reranker, normalize="score").with_row_id(True).to_polars()

Vector Row-IDs are also off when just using a vector query. But for pure vector or pure full-text search its no issue since the order and scores will stay the same.
vectorsearch = table.search(query_embedding, vector_column_name="embeddings").metric(distance_metric).limit(limit).with_row_id(True).to_polars()

**Comment by wjones127** [comment]
> When adding first just 1 million rows and the rest in batches of 100.000 row_ids for vector search are still way off after around a million:

Actually, these row ids are correct. The row id is `(fragment_id << 32) | row offset`. So the third row in the first data file has id `2` and the third row in the second file is `(1 << 32) | 2` which is `4294967298`.

It's the Tantivy FTS index that is wrong. We just assume the row ids are sequential instead of reading them from the table:

https://github.com/lancedb/lancedb/blob/437316cbbc70c0c84dabd804d790c53851dcb07c/python/python/lancedb/fts.py#L119-L143

FYI there is a newer native FTS supported if you pass `use_tantivy=False`. This shouldn't have this issue.

**Comment by jonas768** [comment]
Wow, thank you so much for the quick reply and adjusting the title accordingly.
My current workaround was just replacing the merge function of the LinearCombinationReranker to use my own Chunk_ID.

Any documentation on the differences of the text search implementations tantivy <> native?
Any way to pass a phrase as is without any cleaning and ensure no operators etc. are tracked (pure scoring)?
Thanks!

**Comment by wjones127** [comment]
> I understand the current native FTS does no stemming whatsoever so might be a bit lacking quality wise? I just use pure scoring so no need for search operators etc, but stemming would be good.

True, those features are coming soon.

**Comment by wjones127** [comment]
I thought this would be simple to fix, but unfortunately it's a bit more subtle. I think the better fix will be to switch to the new native FTS indices when those are production-ready.

**Comment by jonas768** [comment]
Thanks for following up. Meanwhile I already migrated to the new Lance FTS search. Stemming does indeed already work for english, that was not so clear in the documentation. I am satisfied and dont have any duplicates anymore.

**Comment by QianZhu** [comment]
https://lancedb.github.io/lancedb/fts/ - stemming added to the docs

**Comment by jonas768** [comment]
> https://lancedb.github.io/lancedb/fts/ - stemming added to the docs

Thats great, thank you.

Minor thing (i believe copy paste error): This example of the native fulltext search is still shown with use_tantivy=True:
table.create_fts_index("text", use_tantivy=True, tokenizer_name="en_stem")
