### ISSUE TITLE
Feature: Same way of connecting to DB synchronously as asynchronously

### ISSUE THREAD

**Issue by JoelNiklaus** [lancedb/lancedb#1764]
### SDK

Python

### Description

Currently, the `connect_async` function expects a `storage_options` parameter. However, the `connect` function does the connection differently, and I cannot use the `storage_options`.
Would it be possible to connect in the same way?

**Comment by wjones127** [comment]
I will be working on consolidating them in the near future. This is tracked in https://github.com/lancedb/lancedb/issues/1616
