### ISSUE TITLE
bug(python): explain_plan does not include prefiltering/scalar indices

### ISSUE THREAD

**Issue by alexkohler** [lancedb/lancedb#1768]
### What happened?

https://github.com/lancedb/lancedb/blob/04e1f1ee4c0c56efc86f7b36e9f08f06983f1de7/python/python/lancedb/query.py#L472-L504

From what I can see from the implementation here, we're not carrying forward `k`, `nprobes`, or `refine_factor` inside of the `nearest` argument and are not passing down any scalar filters/preflter designations.

**Comment by alexkohler** [comment]
If I'm not mistaken, I _think_ the fix would be something as simple as this:
```python
        return ds.scanner(
            nearest={
                "column": self._vector_column,
                "q": self._query,
                "k": self._limit,
                "nprobes": self._nprobes,
            },
            prefilter = self.prefilter,
            filter = self._str_query,
        ).explain_plan(verbose)
```

**Comment by wjones127** [comment]
Yes, that is correct. Though ideally we would pull out a common function so it shares the implementation with this function:

https://github.com/lancedb/lancedb/blob/04e1f1ee4c0c56efc86f7b36e9f08f06983f1de7/python/python/lancedb/table.py#L1798-L1822
