### ISSUE TITLE
bug(python): Is there no metric for async table.vector_search

### ISSUE THREAD

**Issue by kekulai-fredchang** [lancedb/lancedb#1814]
### What happened?

The documentation for async tables states that only the closest vectors will be return for vector_search.  

The corresponding sync tables have the option to choose the metric.  

Is it correct that for the async api as it stands today only euclidean distance is supported?

**Comment by wjones127** [comment]
`metric` was renamed `distance_type` in the async API https://lancedb.github.io/lancedb/python/python/#lancedb.query.AsyncVectorQuery.distance_type
