### ISSUE TITLE
Can lancedb work with Delta Lake

### ISSUE THREAD

**Issue by zhenlohuang** [lancedb/lancedb#182]
In my option, if lancedb can work with Delta Lake, that  would empower Delta Lake with vector search capability.

**Comment by jaichopra** [comment]
@zhenlohuang thanks for the request. Is your data stored in delta format?

**Comment by eddyxu** [comment]
We could not support delta lake directly at the moment. The underneath data format is [lance](https://github.com/lancedb/lance), which has a few different designs compared to parquet / delta lake to make vector search fast.

**Comment by zhenlohuang** [comment]
@jaichopra Yes, we store our data in delta format
