### ISSUE TITLE
Feature:  Vector index is split by K-means into regional clusters, each being a specific size to fit in RAM.

### ISSUE THREAD

**Issue by vtempest** [lancedb/lancedb#1821]
### SDK

Node

### Description

https://airesearch.js.org/functions/addEmbeddingVectorsToIndex.html

Compile hnswlib-node or NGT algorithm C++ to WASM JS for efficient similarity search.
Vector index is split by K-means into regional clusters, each being a specific size to fit in RAM. This is better than popular vector engines that require costly 100gb-RAM servers because they load all the vectors at once.
Vectors for centroids of each cluster are stored in a list in SQL, each cluster's binary quantized data is exported as base64 string to SQL, S3, etc.
Search: Embed Query, Compare to each cluster centroid to pick top clusters, download base64 strings for those clusters, load each into WASM, find top neighbors per cluster, merge results sorted by distance.

**Comment by wjones127** [comment]
Hi @vtempest.

1. We already split our indices into clusters based on k-means. This is the "IVF" part of our `IVF_PQ` and `IVF_HNSW_SQ` indices. Agreed that vector databases that have to load huge amounts of data into memory don't always make sense.
2. We don't yet support WASM as a target, but would definitely like to eventually. We are tracking that in https://github.com/lancedb/lancedb/issues/230
