### ISSUE TITLE
bug(node): Cannot read property of undefined (reading 'create') on getRegistry().get()

### ISSUE THREAD

**Issue by dil-atanko** [lancedb/lancedb#1864]
### LanceDB version

v0.13.0

### What happened?

It should return a promise which returns the embedding function of that particular model.
The only difference what I found:
V0.13.0
![image](https://github.com/user-attachments/assets/8da71803-3ac8-42d1-a128-22f92ad14f89)

V0.12.0 <- it is working right now
![image](https://github.com/user-attachments/assets/bc9f5edf-c5e9-43a6-9e0a-19cf419033ba)

### Are there known steps to reproduce?

Error: TypeError: Cannot read properties of undefined (reading 'create')

Just try it, it wont work :/

_No response_

**Comment by wjones127** [comment]
We had a breaking change in v0.13.0 where we moved the embedding functions to their own entrypoints. You might need to add an additional import. Here is an example with OpenAI:

https://github.com/lancedb/lancedb/blob/162880140e73df095e603489b55c2fac5ca2535e/nodejs/examples/embedding.test.ts#L6

**Comment by dil-atanko** [comment]
Ah, got it, sorry. Maybe a highlighting on that (in the doc) would be nice 👍 
It is a nice work, thanks.

**Comment by nikitpanchal** [comment]
Hi 

I'm also facing the same issue. The get("ollama") is undefined When using ollama.
My ollama server is running

Could you please help ?

![Image](https://github.com/user-attachments/assets/a2e80092-3a24-4cd6-bbe6-977bf2949e6f)
