### ISSUE TITLE
bug(node): Error when trying to do full text search with filter

### ISSUE THREAD

**Issue by chenbb1** [lancedb/lancedb#1877]
### What happened?

Tried to do full text search using filter, the filter filtered all the documents, full text search failed :
2024-11-24T15:49:42Z TRACE lance_encoding::decoder] Draining batch task (rows_remaining=0 rows_drained=4 rows_scheduled=4)
thread 'tokio-runtime-worker' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-index-0.19.1/src/scalar/inverted/wand.rs:208:18:
pivot posting should have at least one document
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
node:internal/modules/run_main:122
    triggerUncaughtException(
    ^

[Error: Failed to get next batch from stream: lance error: LanceError(IO): Execution error: ExecNode(Take): thread panicked: task 27 panicked with message "pivot posting should have at least one document", /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.19.1/src/dataset/scanner.rs:1938:83] {
  code: 'GenericFailure'
}

**Comment by QianZhu** [comment]
Hi @chenbb1 Thanks for reporting the issue. We have a fix for it: https://github.com/lancedb/lance/pull/3163. It will be included in the next Lance release.

**Comment by wjones127** [comment]
This is fixed in the latest release 0.14.0
