### ISSUE TITLE
bug(python): optimize in synchronous context yields error

### ISSUE THREAD

**Issue by kekulai-fredchang** [lancedb/lancedb#1932]
### What happened?

[optimize docs](https://lancedb.github.io/lancedb/python/python/#lancedb.table.Table.optimize) specifies that it works with synchronous connection, but that is not the case. 

```
db = lancedb.connect(uri)
table = db.open_table(table_name)
table.optimize()
```

```AssertionError: Synchronous method called in asynchronous context. If you are writing an asynchronous application then please use the asynchronous APIs```

**Comment by wjones127** [comment]
It's possible you have some other event loop on that thread. For example, I've found `ThreadPoolExecutor` adds one and can cause this error.

I'll be removing this error in #1914
