### ISSUE TITLE
feat(python): add `ignore_missing` to async `drop_table()` method

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#1951]
The sync method has this:

https://github.com/lancedb/lancedb/blob/37c359ed40e860d8f2eec3b72e53ab91a6ad82c8/python/python/lancedb/db.py#L495-L512

But the async method does not:

https://github.com/lancedb/lancedb/blob/37c359ed40e860d8f2eec3b72e53ab91a6ad82c8/python/python/lancedb/db.py#L889-L897

Note that the sync one is a wrapper around the async one, so if you move the implementation to the async, you can remove it from the sync one.

**Comment by nakul-py** [comment]
Hi @wjones127 
I came across this issue and would like to work on resolving it. Could you please assign it to me?
