### ISSUE TITLE
bug(python): AttributeError: 'AsyncTable' object has no attribute 'search'

### ISSUE THREAD

**Issue by anuragmundhada** [lancedb/lancedb#1962]
### LanceDB version

0.14.0

### What happened?

I am trying to use bm25 / full text search with AsyncTable, using 
`res = await table.search(query).limit(k).to_list()`
when I get the following error:
`AttributeError: 'AsyncTable' object has no attribute 'search'`

Does the Async api not support full text search yet?

```
table.__dir__()
['_inner', '__module__', '__doc__', '__init__', '__repr__', '__enter__', '__exit__', 'is_open', 'close', 'name', 'schema', 'count_rows', 'query', 'to_pandas', 'to_arrow', 'create_index', 'add', 'merge_insert', 'vector_search', '_execute_query', '_do_merge', 'delete', 'update', 'version', 'checkout', 'checkout_latest', 'restore', 'optimize', 'list_indices', 'index_stats', 'uses_v2_manifest_paths', 'migrate_manifest_paths_v2', '__dict__', '__weakref__', '__new__', '__hash__', '__str__', '__getattribute__', '__setattr__', '__delattr__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__reduce_ex__', '__reduce__', '__subclasshook__', '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__']```
```

Edit: corrected sparse to full text search

**Comment by wjones127** [comment]
We will be adding the `search()` method in #1938 soon. 

> Does the Async api not support sparse search yet?

What do you mean by "sparse search"? We support (dense) vector search, full text search, SQL filters, and hybrid search.

**Comment by anuragmundhada** [comment]
Thanks for the update!
Meant bm25 search / full text search.

**Comment by wjones127** [comment]
Yes, the async API supports full text search. Use `.query().nearest_to_text(<search terms>)`.

Here is an example:

https://github.com/lancedb/lancedb/blob/27ef0bb0a210de84828309f9b8a561b516deb4e5/python/python/tests/test_fts.py#L245-L251
