### ISSUE TITLE
Can LanceDB be used with dot product for a search metric?

### ISSUE THREAD

**Issue by davidtbo** [lancedb/lancedb#207]
From the docs, it looks like you only supports L2 or cosine metrics. Per the [sentence transformers documentation](https://www.sbert.net/docs/pretrained-models/msmarco-v3.html):

```Models tuned for cosine-similarity will prefer the retrieval of shorter passages, while models for dot-product will prefer the retrieval of longer passages.```

Also from that same page it looks like L2 & cosine are grouped together, separately from the dot product models, so I'm guessing L2 is also better for short retrieval than long retrieval.

Do you have any recommendations for using dot product as a metric in LanceDB?

**Comment by eddyxu** [comment]
Hey, @davidtbo 

We have not yet exposed dot product yet.  It is tracked here https://github.com/lancedb/lance/issues/802. 

We should be able to get it in a few weeks. Feel free to contribute as well

**Comment by changhiskhan** [comment]
Hi there. Yeah currently we only support L2 and cosine distances. As a workaround, if your vectors are pre-normalized, then cosine distance is equivalent to dot product.

**Comment by davidtbo** [comment]
Thanks for the quick answer! :)
