### ISSUE TITLE
Concurrent writes in LanceDB with multiprocessing?

### ISSUE THREAD

**Issue by davidtbo** [lancedb/lancedb#213]
Hello all,

I'm loving LanceDB so far but I am trying to accelerate writes. Since it looks like each row in the database is written as a separate file, it seems possible for multiprocess writes unless there's some locking on the file system in the folders other than data. 

Can you advise how to write to LanceDB from multiple processes at once?  Right now I'm doing this:
```
def trainer():
    global queue
    print(f"Database initializing in process {os.getpid()}")
    db = Db()
    print(f"Initialized database. Beginning doc processing in pid {os.getpid()}")
    db.process_corpus_doc_file()
    print(f"Processing in process {os.getpid()} is complete.")
    
processes = []
for i in range(num_procs):
    # Stick a None in the queue for each process to consume and exit.
    queue.put(None)
    p = mp.Process(target=trainer)
    p.start()
    processes.append(p)
```
Each copy of Db() tries to open a connection to the same LanceDB database and table in parallel, but I only spin up the multiple loader processes after I've initialized the table once in the parent process. Is this a problem? Right now it seems to crash my computer entirely, so I'm guessing it might be causing a race condition or something.

Thanks!

**Comment by wjones127** [comment]
> Since it looks like each row in the database is written as a separate file

This is true, only if you are writing one row at a time. If this is the case, I think before trying multiple processes you might be better off trying to write multiple rows at a time, which is what LanceDB is optimized for. We have parallelism internally, so we can take advantage of multiple cores without the need for multiprocessing.

How are you getting your rows / batches that you are writing? [Our example](https://lancedb.github.io/lancedb/basic/#how-to-add-data-to-a-table) shows using a Pandas dataframe, but if you have Arrow record batches that is written even more efficiently.

**Comment by davidtbo** [comment]
I'm currently reading in a jsonlines file and adding one row at a time. I could batch. However, it takes longer to calculate document embeddings than to save to the database, so it would be most efficient to have many embedding threads writing to the database at once. 

I was trying to calculate the embeddings separately in Sentence Transformers and then save them to the database. If I use your with_embeddings functionality, will it be multi-processor by default without me worrying about multi-processing?

**Comment by wjones127** [comment]
> However, it takes longer to calculate document embeddings than to save to the database

It sounds like the bottleneck is calculating embeddings rather than writing the data. That makes sense given how computationally intensive it can be.

> so it would be most efficient to have many embedding threads writing to the database at once.

Have you considered distributing only the embeddings calculation, and keeping the database write as a single thread? As in: a simple fan-out then fan-in model. That seems like the simplest approach for this use case.

We do support distributed writes, though the API for that isn't well document. But like I said earlier, I don't think this is appropriate for the use case you are describing. This is mostly useful in a distributed system where there are multiple independent nodes; for single-node systems the single-process writer will utilize your IO resources pretty well.

To be clear: if you write one row per file in LanceDB, we can't promise good performance. There is overhead for each file in the table, and this overhead is meant to be amortized over thousands to millions of rows. We'll likely provide utilities functions to compact small files into larger ones to optimize existing tables, but we don't have that yet. So for the sake of good read performance, I'd encourage you to write in batches.

**Comment by davidtbo** [comment]
I'm running using your advice now, and I'm using with_embeddings instead of running my embedder in a separate thread, since you said you handle all the optimization of multiprocessing. I see that it's maxing out at 200% on a 4-processor box, so it doesn't really seem to be optimized to use all of the processors.

Can you advise? Am I doing something wrong? See my top screenshot below. 
<img width="754" alt="image" src="https://github.com/lancedb/lancedb/assets/14362389/1dd126fb-bd80-4ac4-8ec8-44996753604f">

**Comment by wjones127** [comment]
> I'm using with_embeddings and writing in batches instead of running my embedder in a separate thread, since you said you handle all the optimization of multiprocessing

Sorry, I didn't mean to imply `with_embeddings` uses multiple threads. AFAIK it does not.

My suggestion was to write a "fan-out fan-in" program with three process types:


```mermaid
  graph LR;
      read_worker-->embedding_worker_1;
      read_worker-->embedding_worker_2;
      read_worker-->embedding_worker_3;
      read_worker-->embedding_worker_4;
      embedding_worker_1-->write_worker;
      embedding_worker_2-->write_worker;
      embedding_worker_3-->write_worker;
      embedding_worker_4-->write_worker;
```

1. `read_worker` A process that reads the JSON lines and sends them to the embeddings workers
2. `embedding_worker` N processes that generate embeddings for rows they are given, then sends the to the write worker
3. `write_worker` A process that collects rows into batches and writes them to lance once a sufficient number have been collected.

This way, you parallelize the CPU-bound part (computing embeddings), but batch it all in one writer. Does that make more sense now?

We could eventually make `with_embeddings` do this for you.

**Comment by davidtbo** [comment]
That does make sense. Thanks!

**Comment by changhiskhan** [comment]
Please feel to reopen if you're still having the same issue
