### ISSUE TITLE
Allow replacing an index

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#214]
Expose the `replace` param in create_index''https://lancedb.github.io/lance/api/python/lance.html#lance.dataset.LanceDataset.create_index

**Comment by Harshal662** [comment]
def create_index(column: str,
                 index_type: str,
                 name: str | None = None,
                 metric: str = 'L2',
                 replace: bool = False,
                 num_partitions: int | None = None,
                 ivf_centroids: ndarray | FixedSizeListArray | None = None,
                 num_sub_vectors: int | None = None,
                 **kwargs):
    if replace:
        # Logic for replacing an existing index
        print("Replacing existing index")
    else:
        # Logic for creating a new index
        print("Creating new index")


like this u are saying?

**Comment by wjones127** [comment]
It's even simpler than that.

In this function:
https://github.com/lancedb/lancedb/blob/b489edc5766f541b6ab969ef69834563772666e0/python/lancedb/table.py#L185-L207

Add a new parameter `replace: bool`, and then pass that into `self._dataset.create_index(`

**Comment by Harshal662** [comment]
def create_index(self, metric="L2", num_partitions=256, num_sub_vectors=96, replace: bool = False):
    self._dataset.create_index(
        column=VECTOR_COLUMN_NAME,
        index_type="IVF_PQ",
        metric=metric,
        num_partitions=num_partitions,
        num_sub_vectors=num_sub_vectors,
        replace=replace,  # Pass the replace parameter
    )
    self._reset_dataset()


like this
