### ISSUE TITLE
Support pre-filtering in LanceDB

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#261]
From the interface aspect, we could add one method

```python
Table::prefilter(filter: str)
```

which will apply a filter in lancedb first, and run vector search over the filtered results.

**Comment by beasteers** [comment]
This would be great because if your filters are too strict you currently can very easily end up with an empty query.

The alternative is pre-creating different tables for each query beforehand but that has obvious downsides (that's what you have to do with faiss for example).

**Comment by rishabhRsinghvi** [comment]
@eddyxu can you assign this to me?

**Comment by westonpace** [comment]
@rishabhRsinghvi we've actually had prefiltering support in lancedb for a while, as long as there is no vector index.  Lance (the format) now also supports prefiltering with a vector index.  So the only thing that remains is to remove a check that was in lancedb preventing prefilter with vector index.  I will probably be doing this today.
