### ISSUE TITLE
[Docs] Python integrations cleanup

### ISSUE THREAD

**Issue by TevinWang** [lancedb/lancedb#288]
Remove "Out[16]:" from python integrations documentation page:
<img width="707" alt="Screen Shot 2023-07-12 at 2 50 08 PM" src="https://github.com/lancedb/lancedb/assets/43354492/965b25f4-d0dc-4210-8e87-0b68e3f64204">

**Comment by unkn-wn** [comment]
Also fix the `'` in the example at the bottom of [this page](https://lancedb.github.io/lancedb/embedding/)
![image](https://github.com/lancedb/lancedb/assets/43097991/63493892-3f78-4211-a6a8-3e9ee21d8308)
