### ISSUE TITLE
Cannot Open Table Stored On S3

### ISSUE THREAD

**Issue by Wildhammer** [lancedb/lancedb#295]
The `open` method under `LanceTable` object does this check `os.path.exists(tbl._dataset_uri)` which is only applicable to when files stored locally. In the event of persisting to S3 (`s3://my-bucket/path/to/root`) this check fails and returns the error message `Table {name} does not exist` while if you call the `table_names` method you can see that the `DBConnection` object has successfully connected to S3 and returning the existing table names.

Should be an easy fix I'd be glad to help just let me know how I can create a PR for this.

Thanks

**Comment by Wildhammer** [comment]
Basically the condition check needs to be modified to 

```python
if not os.path.exists(tbl._dataset_uri) and "s3://" not in tbl._dataset_uri
```

**Comment by eddyxu** [comment]
Thanks for reporting the bug @Wildhammer . 

It seems that we missed the code change in `LanceTable::open()`. Usually, you can open a s3 table via

```python
db = lancedb.connect("s3://base/path")
table = db.open_table("table_name")
```

Welcome to contribute!  we might want to just delete `open()` method , given that it is functionally the same as `LanceTable.__init__()`.

**Comment by Wildhammer** [comment]
Thanks, it's all working now. 

```python
db = lancedb.connect("s3://base/path")
table = LanceTable(db, "table_name")
```

**Comment by eddyxu** [comment]
Fixed in https://github.com/lancedb/lancedb/pull/326 as well
