### ISSUE TITLE
Make a field optional

### ISSUE THREAD

**Issue by wangdong2023** [lancedb/lancedb#354]
I actually don't know if it's possible, I tried the example in `Langchain` documents, and then I found that I can't add data if one of the metadata fields is missing. The error message is `'Field "source" does not exist in table schema'` which is super misleading, because it looks like there's a unexpected field, but in reality it's a missing field.

I tried to state in the pyarrow schema that the 'source' field is optional, then I found it already is, so problem should be on the `lancedb` side. I tried to search for relevant document, but I can't find much. 

I hope `lancedb` can have optional fields, and if it already does, have a document on how we can use optional fields. I saw other issues demanding schema evolution, I think that's pretty useful for us as well.

**Comment by eddyxu** [comment]
@wangdong2023 LanceDB uses Arrow, you can set a field with optional values.

**Comment by wangdong2023** [comment]
@eddyxu I already did, I don't know if latest release fixed this, but at that time, stating it as optional doesn't have the effect fo allowing null values in lancedb.
