### ISSUE TITLE
Error when adding null values to LanceDB

### ISSUE THREAD

**Issue by gsilvestrin** [lancedb/lancedb#362]
`Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: InvalidArgumentError("Column 'name' is declared as non-nullable but contains null values")`

```
      const data = [
        { id: 1, vector: [0.1, 0.2], price: 10, name: null }
      ]

      const table = await con.createTable('vectors', data)
```

**Comment by QianZhu** [comment]
fixed
