### ISSUE TITLE
Sort table names

### ISSUE THREAD

**Issue by westonpace** [lancedb/lancedb#425]
Table names are currently generated by listing the directories in the db base uri.  However, there is no guarantee in what order the table names will be returned and the order can depend on table creation time or the user's filesystem (e.g. osx sorts for you, linux does not).

It would be a friendlier interface if we sort these alphabetically for the user so that the output will be consistent regardless of how the db was built and what machine the user is using.

**Comment by westonpace** [comment]
See https://discord.com/channels/1030247538198061086/1105226935333818532/1139322703845789756 for motivation

**Comment by ashiskumarnaik** [comment]
@westonpace Right , I faced that issue while comparing the search results.
