### ISSUE TITLE
[Python] Allow setting embedding functions during table creation & ingest it 

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lancedb#447]
```
db.create_table(..., metadata={...})
```
This would be useful to be able to (optionally) serialize the embedding functions when creating a table, calculating vector column as the data comes in.

(Can also support default vectorizers which are pretty cool and abstract away the need to vectorize manually)
```
db.create_table(..., embedding_func=callable) # -> serialize this func as metadata
tbl = db.open(..)
tbl.add(...) # -> check if embedding_func exists in metadata, and calculate embeddings before running _santize_data
```

**Comment by changhiskhan** [comment]
1. For custom functions we could pickle the embedding function and store the bytes as metadata in the lance dataset itself (pyarrow Table metadata).
2. We can declare a standard set of functions (openai, cohere, sentence-transformers, etc) and store some standard representation as table metadata.
3. Additional, the user can specify the source column name and output vector column name (so you could have multiple vector columns with different embedding functions etc)
4. The tricky part about custom functions is the dependencies. How do we manage them across environments for example.

**Comment by AyushExel** [comment]
4 will just raise an ImportError?

**Comment by changhiskhan** [comment]
i'm going to close this as we have an initial implementation. We can refine based on feedback.
