### ISSUE TITLE
Lance DB in Nextjs

### ISSUE THREAD

**Issue by koolamusic** [lancedb/lancedb#448]
I am not sure what the issue is, but I think there is a challenge with how nextjs bundles api routes which doesn't work with LanceDB.

going to include the error stack trace below

```
- error ./node_modules/vectordb/node_modules/@lancedb/vectordb-darwin-x64/README.md
Module parse failed: Unexpected character ' ' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> # `@lancedb/vectordb-darwin-x64`
|
| Prebuilt binary package for `vectordb` on `darwin-x64`.

Import trace for requested module:
./node_modules/vectordb/node_modules/@lancedb/vectordb-darwin-x64/README.md
./node_modules/vectordb/node_modules/@lancedb/ ./node_modules/@lancedb/ sync ^\.\/vectordb\-.*$
./node_modules/vectordb/native.js
./node_modules/vectordb/dist/index.js
./app/api/chat/route.ts
```

**Comment by AyushExel** [comment]
Hi @koolamusic vectordb's node binding (index.node) needs a plugin to be parsed by webpack when bundling. You can either use that or simply ignore that file. Please see how you can configure webpack to make this work on our docs - https://lancedb.github.io/lancedb/basic/#note-bundling-vectordb-apps-with-webpack

**Comment by koolamusic** [comment]
Thanks for the prompt feedback. This was super helpful. I had initially found a way around that is more like sorcery. 

```js
   webpack: (config, { isServer }) => {
      if (isServer) {
        config.externals = [
          ...config.externals,
          // @ts-ignore
          function ({ context, request },  callback) {
            if (request.endsWith('.node') || request.includes('vectordb') || request.includes('@lancedb/vectordb-darwin-x64/README.md')) {
              return callback(null, 'commonjs ' + request);
            }
            callback();
          },
        ];
      }
  
      return config;
    },
    ```
    
    
    But the solution you've shared is way more cleaner. 🤟🏾

**Comment by koolamusic** [comment]
Thanks for the prompt feedback. This was super helpful. I had initially found a way around that is more like sorcery. 

```js
   webpack: (config, { isServer }) => {
      if (isServer) {
        config.externals = [
          ...config.externals,

          function ({ context, request },  callback) {
            if (request.endsWith('.node') || request.includes('vectordb') || request.includes('@lancedb/vectordb-darwin-x64/README.md')) {
              return callback(null, 'commonjs ' + request);
            }
            callback();
          },
        ];
      }
  
      return config;
    },
    ```
    
    
    But the solution you've shared is way more cleaner. 🤟🏾

**Comment by koolamusic** [comment]
@AyushExel can't find it in the docs, but how do I do a where

```
await table
    .search(currentMessageContent)
    .where(`type = "post" or type="image"`)
    // .orderBy(`cosine_similarity(${VECTOR_SOURCE_COLUMN}, "${currentMessageContent}")`)
    .select(['type', 'text', 'url'])
    .limit(2)
    .execute();
    ```

**Comment by coderphonui** [comment]
> Hi @koolamusic vectordb's node binding (index.node) needs a plugin to be parsed by webpack when bundling. You can either use that or simply ignore that file. Please see how you can configure webpack to make this work on our docs - https://lancedb.github.io/lancedb/basic/#note-bundling-vectordb-apps-with-webpack
> 
> Let me know if you face any problems :)

It seems this link is updated with new content and I found ref information related to webpack on that page. I got the same issue. Could you please share me how did you fix this problem?
