### ISSUE TITLE
Does this support Python 3.6?

### ISSUE THREAD

**Issue by gitlGl** [lancedb/lancedb#461]

**Comment by westonpace** [comment]
The code is currently tested on python 3.8, 3.9, 3.10, and 3.11.  Python 3.6 has been end-of-life for quite some time now.  It would be rather challenging to support.  What sort of environment do you have that requires python 3.6?

**Comment by gitlGl** [comment]
The library I'm using is called dlib. It only supports Python 3.6, and for versions above Python 3.6, I need to compile and install it myself. However, I've found that the memory usage of the compiled version is exceptionally high. So, I'm limited to using Python 3.6.

**Comment by gitlGl** [comment]
> The code is currently tested on python 3.8, 3.9, 3.10, and 3.11.  Python 3.6 has been end-of-life for quite some time now.  It would be rather challenging to support.  What sort of environment do you have that requires python 3.6?

The library I'm using is called dlib. It only supports Python 3.6, and for versions above Python 3.6, I need to compile and install it myself. However, I've found that the memory usage of the compiled version is exceptionally high. So, I'm limited to using Python 3.6.

**Comment by westonpace** [comment]
I don't think it will be possible to support python 3.6.  As an example of one challenge, lancedb's core is a rust project.  The rust/python adapter (pyo3) [dropped python 3.6 over a year ago](https://github.com/PyO3/pyo3/commit/70030f130dd9ad67e49af12a1ac9cb04c2ec0ca7).  It would be very challenging to try and use/maintain these older tools.
