### ISSUE TITLE
where filter without vector search

### ISSUE THREAD

**Issue by oldrich-s** [lancedb/lancedb#470]
Is it possible to filter and retrieve from the database only based on SQL where clause and without the vector similarity search?

Does the delete SQL query perform full DB scan to find the rows to be deleted?

Thanks 😊

**Comment by eddyxu** [comment]
> Is it possible to filter and retrieve from the database only based on SQL where clause and without the vector similarity search?

Yes, we are discussing how to revamp the API design to expose such capability 
https://github.com/lancedb/lancedb/issues/462

In the meantime, you can do

```
tbl.to_lance().scanner(filter="col1 = 20 AND col2 = 500").to_df()
```
to access the data.


> Does the delete SQL query perform full DB scan to find the rows to be deleted?

Yes, that's right.

**Comment by oldrich-s** [comment]
thanks

**Comment by samlhuillier** [comment]
Does this also work in javascript? As far as I can tell it doesn't...
