### ISSUE TITLE
Update langchain integration & example to use empty table initialization

### ISSUE THREAD

**Issue by AyushExel** [lancedb/lancedb#471]
The current example on langchain docs front page is much more complex than it needs to be. 

* Needs to be using empty tables with schema. would better showcase the capabilities
* User should not even need to to define the table manually (or even import lancedb), it should be handled by the integration itself (see the other 2 in the examples) 
Ideally, the usage should be something like this:
```
from langchain.document_loaders import TextLoader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import LanceDB

raw_documents = TextLoader('../../../state_of_the_union.txt').load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
documents = text_splitter.split_documents(raw_documents)
db = LanceDB.from_documents(documents, OpenAIEmbeddings()) # optional args -> uri, existing table ref for backwards compat.
```
Source - https://python.langchain.com/docs/modules/data_connection/vectorstores/
<img width="1437" alt="Screenshot 2023-09-04 at 4 57 08 AM" src="https://github.com/lancedb/lancedb/assets/15766192/0d936132-c5f2-42a2-b282-e0387e1cef1b">

**Comment by changhiskhan** [comment]
We need to update all of the integrations to reflect the change from score to _distance as well
