### ISSUE TITLE
[Python] Pydantic vector field does not take default value

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#473]
# Problem Statement

We have provide a vector field for Pydantic based models. However the vector field does not take default value as others default fields.

![image](https://github.com/lancedb/lancedb/assets/17097/5dee87d5-8f14-4482-93b6-2fc30887bafd)
![image](https://github.com/lancedb/lancedb/assets/17097/5b06b2f7-8564-45dc-9c0b-09b7f49f81eb)

**Comment by eddyxu** [comment]
https://github.com/lancedb/lancedb/pull/474. Would not reproduce the problem in the PR.

**Comment by changhiskhan** [comment]
@eddyxu i think this can be closed as completed right?
