### ISSUE TITLE
lancedb connector functionality does not work with azure url path

### ISSUE THREAD

**Issue by EmilijaL** [lancedb/lancedb#485]
create_table() works with azure url path to blob storage, but other functionality like table_names()  or open_table()  throws error

**Comment by changhiskhan** [comment]
What's the error?

**Comment by EmilijaL** [comment]
It works creating table:
![create_table](https://github.com/lancedb/lancedb/assets/32243027/652144e9-4817-4edc-b462-f1091b483b2f)

But other methods throw error:
![open_database](https://github.com/lancedb/lancedb/assets/32243027/a4bef0b9-cf43-4f6f-97f6-a244387dfdd8)
![table_names](https://github.com/lancedb/lancedb/assets/32243027/107dac00-d7af-4699-8b7f-9da1694507d1)

**Comment by westonpace** [comment]
This should have been fixed by https://github.com/lancedb/lancedb/pull/1102
