### ISSUE TITLE
create_fts_index creates duplicates

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#498]
Reported by catethos on discord

"call the 'create_fts_index' twice will double the index instead of replacing it, i.e. i would get twice of the same row when i do the search"

**Comment by prrao87** [comment]
I found this bug too, and my current workaround is to ensure that I clear out the FTS index directory prior to running the function. It would be nice to have it just update the FTS index (without duplicates) as and when we need to add new data in an incremental fashion - rebuilding the entire index seems like a waste each time!

**Comment by wjones127** [comment]
This seems to be a big foot gun.
