### ISSUE TITLE
lancedb/python depends on `attr` package, not `attrs`

### ISSUE THREAD

**Issue by rec** [lancedb/lancedb#509]
Hello, LanceDb maintainers!  Thanks for a great package, I use it every day.

## The issue

We have found a fascinating issue in your dependencies that is mostly caused by errors beyond your control. :-D. We believe it is also the cause of your https://github.com/lancedb/lancedb/issues/387

Write-up is here:  but I'll summarize it for you.

Looking at [this line](https://github.com/lancedb/lancedb/blob/main/python/lancedb/remote/__init__.py#L47), you would expect that it would be using the PyPi library [`attr`](https://pypi.org/project/attr/), but if you look at the [code](https://github.com/denis-ryzhkov/attr/blob/master/dry_attr.py), there is no `.define` property!

This worked for us for months, but now [fails on a new installation](https://github.com/SuperDuperDB/superduperdb/issues/983).

## The cause

In fact, the [`attrs`](https://www.attrs.org/en/stable/) project installs two modules, `attrs` and `attr`, and that's what you're actually using, and it has an `attr.define` decorator.

However, [the dependency is on `attr`](https://github.com/lancedb/lancedb/blob/74004161ff1a90ae11a7fa531b551b2bc891e6ed/python/pyproject.toml#L11), which is a tiny, unrelated project.

If you check your Python environment, you will see that there are both `attr.py` and an `attr/` module installed.

Now, apparently in most installations Python uses the directory, but in that new environment, it prefers the .py file, and so gets the tiny `attr.py` module and emits and error.

## The solution

It's a one character change!  I'll send it out immediately after this as a pull request, but I still haven't figured out how to run the tests, your guidance is solicited.

**Comment by chebbyChefNEQ** [comment]
done by #508
