### ISSUE TITLE
The term "pylance" in for the Python client is potentially misleading

### ISSUE THREAD

**Issue by prrao87** [lancedb/lancedb#51]
Hi, this looks like a fascinating project, thanks a lot for making this happen! Looking forward to using it and spreading the word.

Regarding the name `pylance` for the Python client, was the name `lancedb` not available on pyPI? It's unfortunate that the Microsoft VS Code team chose the name "Pylance" for their Python language server, and there's a separate [Github repo](https://github.com/microsoft/pylance-release) for this, that can lead people who arrive from a Google search to the wrong project. `pip install lancedb` would be very consistent with the general ecosystem of serverless, in-memory databases  (like `pip install duckdb`).

Since it's early days for the project, is it possible to change the name on pyPI before this becomes an SEO nightmare? In any case, have given this repo a star and will spread the word, thanks!

**Comment by prrao87** [comment]
Okay, having read through a few more docs and blog posts, I'm a little confused about what packages to install for using Lance via Python.

[This blog post](https://blog.eto.ai/benchmarking-random-access-in-lance-ed690757a826) that led me here mentions `pip install pylance`; however, this repo's README says it's `pip install lancedb`. If the latter is the current status, please close this issue. Thanks again!

**Comment by changhiskhan** [comment]
Hi @prrao87 thanks for the feedback and the star! We're grateful for your support!

Real quickly: 
1. Lance is the OSS columnar data format. It has a python package called `pylance` (lance was taken already).
2. LanceDB is the OSS vector database. It has a python package called "lancedb" (thankfully that was not taken).

The reason why we have 2 repos is that Lance format is more general purpose (columnar data store for unstructured AI data). LanceDB is (for now) very focused on vector search, especially for recsys and generative AI.

Happy to chat in more detail if you have any additional questions / concerns.

Thanks!

**Comment by prrao87** [comment]
Ah, this explanation makes so much more sense, thanks! I hadn't heard of Lance's columnar format before, but it really looks promising! The distinction between the two repos makes a lot of sense, as do their names in PyPI.

The Rust ecosystem is just so exciting these days, and I'm sure you'll see great success with this! Good luck, and looking forward to using LanceDB for vector querying! 👊🏽
