### ISSUE TITLE
limit trouble

### ISSUE THREAD

**Issue by westwooder** [lancedb/lancedb#511]
SQLTemplate = '''(name='xxx')'''

name= 'aaaa'
info = '''bbbbb
'''

sentences=[]
sentences.append(info)

sql = SQLTemplate.replace('xxx',name)
print(sql)
dfShow = tbl.search(model.encode(sentences)[0],'vector').where(sql).limit(1).to_df()

Search using the above code. If the limit value is less than 5, the return value will be empty in certain cases, and if it is greater than 5, it will be randomly returned, which feels like a bug

**Comment by changhiskhan** [comment]
Currently the limit is part of the knn/ann search then the where filter is applied afterwards. This is post-filtering. 

We're also working pre-filtering, where the filter is applied first before limit.

**Comment by westwooder** [comment]
@changhiskhan Thank you for your reply. How to implement pre filtering in the code？

**Comment by changhiskhan** [comment]
we merged in a partial implementation: https://github.com/lancedb/lance/pull/1276
We'll expose this to LanceDB and then make a release soon

**Comment by changhiskhan** [comment]
Prefiltering has been implemented. Please refer to our documentation on how to use it (python and javascript). Thanks!
