### ISSUE TITLE
improve example for using iterators

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#532]
user report:

in https://lancedb.github.io/lancedb/guides/tables/#using-iterators-writing-large-datasets, we show the following example:

```
import pyarrow as pa

def make_batches():
    for i in range(5):
        yield pa.RecordBatch.from_arrays(
            [
                pa.array([[3.1, 4.1], [5.9, 26.5]],
                        pa.list_(pa.float32(), 2)),
                pa.array(["foo", "bar"]),
                pa.array([10.0, 20.0]),
            ],
            ["vector", "item", "price"],
        )

schema = pa.schema([
    pa.field("vector", pa.list_(pa.float32(), 2)),
    pa.field("item", pa.utf8()),
    pa.field("price", pa.float32()),
])

db.create_table("table4", make_batches(), schema=schema)
```

It was unclear whether the value `2` in `pa.list_` refers to the number of vectors or the number of dimensions since it's 2x2.

Solution: make the shape rectangular instead of a square to disambiguate.

**Comment by litanlitudan** [comment]
Hi @changhiskhan, just addressed this issue in this PR: https://github.com/lancedb/lancedb/pull/533.
