### ISSUE TITLE
Unify to_pandas() and to_df() for a cleaner API interface

### ISSUE THREAD

**Issue by litanlitudan** [lancedb/lancedb#545]
Hi community, love this amazing tool! Just a nit while using the API, seems LanceDB are mixing to_pandas() and to_df() together. Was wondering, shall we unify these two interface for a cleaner API interface design? 🔥🔥🔥

**Comment by changhiskhan** [comment]
I think that's a good idea. I probably favor the to_pandas syntax since that's the same as in pyarrow. We can temporarily support both and add a deprecation warning for to_df and remove it later
