### ISSUE TITLE
Docs for user experience

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#546]
- [x] filtering #523 #559
- [x] ingestion: accepted data types, schema, etc
- [x] #551
- [x] #564
- [x] #566
- [ ] #565
- [x] #563

**Comment by changhiskhan** [comment]
@AyushExel anything major I'm missing here? We should dive up this list across the team and make some meaningful progress.

**Comment by AyushExel** [comment]
https://github.com/lancedb/lancedb/pull/553 - should address the 2nd point.. If there's something missing we can probably create more granular todos in this thread as well

**Comment by prrao87** [comment]
@changhiskhan do you think it's possible to link to the source code on GitHub directly from the Python API docs page? Not sure how the MkDocs integration works, but currently, when I have a question about how the [`to_pydantic`](https://lancedb.github.io/lancedb/python/python/#lancedb.query.LanceQueryBuilder.to_pydantic) method is implemented and want to inspect the source code, I'd have to manually go to GitHub and search for it.

**Comment by changhiskhan** [comment]
That's a great idea. We'll look into it.

**Comment by prrao87** [comment]
Handling this in #683, closing for now.
