### ISSUE TITLE
Field_by_name is deprecated in pyarrow 13

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#548]
lance/dataset.py:216: FutureWarning: The 'field_by_name' method is deprecated, use 'field' instead

**Comment by westonpace** [comment]
This is fixed in https://github.com/lancedb/lance/pull/1361

**Comment by prrao87** [comment]
Are these changes reflected in `setup.py` and `pyproject.toml`? `pip install lancedb` still seems to be picking `pylance==0.8.1`, reproducing this error 😅

**Comment by changhiskhan** [comment]
@prrao87 it should be updated with the latest lancedb release that went out early this morning.
