### ISSUE TITLE
does search has caching? 

### ISSUE THREAD

**Issue by archywillhe** [lancedb/lancedb#557]
Hi. I would like to use this in production;

Does search API provide caching right now (so we don't embed the same string again)

**Comment by changhiskhan** [comment]
@archywillhe are you using the embedding function registry in python? It wouldn't be terribly hard to add a configurable embedding cache in-memory for this purpose. Would that suffice?

Something like:

```python
db = lancedb.connect("/tmp/db")
registry = EmbeddingFunctionRegistry.get_instance()
func = registry.get("sentence-transformers").create(device="cpu", cache_size=100)
```

where the `cache_size=100` configures an LRU_CACHE of max size 100.

Then to use it:

```python
# make the schema
class Words(LanceModel):
    text: str = func.SourceField()
    vector: Vector(func.ndims()) = func.VectorField()

# create the table with some data
table = db.create_table("words", schema=Words)
table.add(
    [
        {"text": "hello world"}
        {"text": "goodbye world"}
    ]
)

# search
query = "greetings"
actual = table.search(query).limit(1).to_pydantic(Words)[0]
print(actual.text)
```

And if you search multiple times with the same query, then your end-to-end latency (including the embedding) should be much lower. 

wdyt?

**Comment by archywillhe** [comment]
oh thanks for the pointer; sorry I forgot to mention I'm running it on JS. Doesn't look like there is `EmbeddingFunctionRegistry` equivalence there but it's alright I have implemented a cache layer myself
