### ISSUE TITLE
support nested pydantic schema

### ISSUE THREAD

**Issue by pchalasani** [lancedb/lancedb#562]
Defining a table with a nested pydantic schema works fine, but when adding data I get an error.

```
class Document(BaseModel):
     content: str
     source: str

class LanceSchema(LanceModel):
    id: str
    vector: Vector(1536)
    payload: Document

tbl = db.create_table("mytable", schema=LanceSchema, mode="overwrite") # works
tbl.add( [ LanceSchema(id=..., vector = ..., payload = Document(...) ]). # fails with error below

(error was copied from a slightly different version, but you get the idea)

pyarrow.lib.ArrowInvalid: Could not convert Document(content='hello', metadata=DocMetaData(source='context', is_chunk=False, id='0')) with type Document: did not recognize Python value type when inferring an Arrow data type
```

**Comment by changhiskhan** [comment]
Thanks, i'll take a look this week.

**Comment by pchalasani** [comment]
I am currently using a workaround -- I found a way to flatten the Pydantic schema while storing into lancedb, and recover nested Pydantic object from the search results, e.g. you can see here and elsewhere:
https://github.com/langroid/langroid/blob/main/langroid/vector_store/lancedb.py#L131

**Comment by changhiskhan** [comment]
@pchalasani this should be addressed by #707. If you have additional comments/concerns happy to address them.

**Comment by pchalasani** [comment]
Thanks @changhiskhan  
Will this work in the reverse direction, i.e. can I recover the nested pydantic object back from search results? I guess I would do that myself? (not an issue either way). I will check this in a day or two.

**Comment by changhiskhan** [comment]
> Thanks @changhiskhan  
> 
> Will this work in the reverse direction, i.e. can I recover the nested pydantic object back from search results? I guess I would do that myself? (not an issue either way). I will check this in a day or two.

Yup you can. If you take a look at the unit test in the PR I merged, I check that the roundtrip succeeds. We should have another release likely early next week. Or you can install from main if you like to get an early preview

**Comment by pchalasani** [comment]
@changhiskhan so this should work with 0.3.6 right?
