### ISSUE TITLE
API docs should link back to the source code on github

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#563]
Originally mentioned in #546 ; splitting out for better tracking / visibility

**Comment by rok** [comment]
As per [SO](https://stackoverflow.com/questions/75785663/mkdocs-mkdocstrings-add-link-back-to-github-source-code) there currently isn't a good option to link to source. However mkdocstring provides a `show_source` setting that will display the function's source. Example of how that looks like below:
![image](https://github.com/lancedb/lancedb/assets/54589/f4d41290-8fd5-4833-8747-6697e39dea88)
![image](https://github.com/lancedb/lancedb/assets/54589/9ec7d585-9dee-40ab-bd18-c24a49dacb94)
