### ISSUE TITLE
Document query option details

### ISSUE THREAD

**Issue by changhiskhan** [lancedb/lancedb#566]
The docs should have a page going into details on the different query options:

1. different metrics
2. filtering etc
3. limit
4. nprobes / refine_factor

**Comment by QianZhu** [comment]
@changhiskhan 
Is there a doc format that should be used?

**Comment by changhiskhan** [comment]
Same format as the existing docs?

**Comment by QianZhu** [comment]
https://github.com/lancedb/lancedb/pull/615
