### ISSUE TITLE
Indexing with custom metric

### ISSUE THREAD

**Issue by juan-sv** [lancedb/lancedb#590]
Hello,

Is it planned to include custom metric to the indexing feature? Is there any way to implement custom metric?

Thanks

**Comment by eddyxu** [comment]
Hi @juan-sv  

We dont have plan to support custom metric yet. Which metric you see missing currently?

The metrics we supported are implemented here 
https://github.com/lancedb/lance/tree/main/rust/lance-linalg/src/distance
