### ISSUE TITLE
Does lanceDB support distributed?

### ISSUE THREAD

**Issue by wusf233** [lancedb/lancedb#591]
Does lanceDB support distributed?

**Comment by wjones127** [comment]
LanceDB is designed to scale by separating compute compute and storage. In LanceDB OSS, you can choose which storage you use. If you want to distribute queries across multiple machines, use a storage layer that is accessible from multiple machines. For example, use a networked filesystem like AWS EFS. Or if lower cost is more important that low latency, object storage like S3.

```
 ┌────────────────┐
 │                │
 │ LanceDB client ├───────────┐
 │                │           │
 └────────────────┘           │
                              │
 ┌────────────────┐      ┌────▼────┐
 │                │      │         │
 │ LanceDB client ├─────►│ Storage │
 │                │      │         │
 └────────────────┘      └────▲────┘
                              │
 ┌────────────────┐           │
 │                │           │
 │ LanceDB client ├───────────┘
 │                │
 └────────────────┘
```

**Comment by oswardlx** [comment]
> LanceDB 的设计目标是通过分离计算和存储来实现扩展。在 LanceDB OSS 中，您可以选择使用哪种存储。如果您希望将查询分布到多台机器上，请使用可从多台机器访问的存储层。例如，使用 AWS EFS 等联网文件系统。或者，如果低成本比低延迟更重要，则可以使用 S3 等对象存储。
> 
> ```
>  ┌────────────────┐
>  │                │
>  │ LanceDB client ├───────────┐
>  │                │           │
>  └────────────────┘           │
>                               │
>  ┌────────────────┐      ┌────▼────┐
>  │                │      │         │
>  │ LanceDB client ├─────►│ Storage │
>  │                │      │         │
>  └────────────────┘      └────▲────┘
>                               │
>  ┌────────────────┐           │
>  │                │           │
>  │ LanceDB client ├───────────┘
>  │                │
>  └────────────────┘
> ```

How can I adapt Lancedb to other object storage middleware, not S3, other or my custom storage
