### ISSUE TITLE
table.to_arrow for javascript

### ISSUE THREAD

**Issue by samlhuillier** [lancedb/lancedb#625]
Is this coming? I see it's a thing in python and would be eager to use it in js. Basically just looking for table scans with no distance calculations which I don't think is possible right now in javascript.

**Comment by changhiskhan** [comment]
arrow-js is pretty wonky so we haven't integrated. Would it work to just have like a `to_json` method that returns a list of json objects corresponding to each row in the table scan?

**Comment by samlhuillier** [comment]
Thank you for getting back to me on this. 
At the time of the issue, I was more concerned with performing a filter without doing a vector search. I saw there were various issues on this, so wanted to approach the problem from a different angle and convert to an arrow object then manually do the filter. Now that filter has been merged (thank you for that!) I no longer need to_arrow.
