### ISSUE TITLE
Provide a function to make Query Results returned as a list of dict

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#67]
Currently we only support `.to_df()` on the Query object.

**Comment by prrao87** [comment]
As an add-on to this, does it make sense to name the `to_df()` method more explicitly to reference to pandas? This would make it more consistent to the `to_pandas` method in the table API. Also, it would be awesome to be able to export the query result `to_arrow()`, `to_pandas()` or `to_polars()`, for both the table and query result APIs, to keep things consistent and easy to remember.

**Comment by changhiskhan** [comment]
we have `to_list()` now
