### ISSUE TITLE
Document how to configure object stores

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#681]
There are various environment variables we accept. For example, for S3, we take these:

https://docs.rs/object_store/latest/object_store/aws/struct.AmazonS3Builder.html#method.from_env

We should document how to use these. A common use of them is credentials, but also how to connect to S3-compatible stores.

**Comment by changhiskhan** [comment]
@wjones127 I see you've already added some of this to the lance format docs. Would you mind adding a section for lancedb docs?

I was thinking you can put this under the "Guides" section in a new page called "Cloud storage" or something like that?

It would be great to have both python and js examples

**Comment by wjones127** [comment]
Yes I plan to do this soon.

**Comment by lenage** [comment]
does lancedb support  S3 Express One storage type?

**Comment by wjones127** [comment]
> does lancedb support S3 Express One storage type?

Not yet, but we are actively looking into it.
