### ISSUE TITLE
[Feature] Can IVF-PQ index table support incremental update?

### ISSUE THREAD

**Issue by amulil** [lancedb/lancedb#684]
When I don't use IVF-PQ index, I can use this metheod to have an incremental update:
```python
tbl = db.open_table(index_name)
predicate = f'id = {id}'
tbl.delete(predicate)
tbl.add(data=data)
```
When I use IVF-PQ index on this table, Can I use the same method to have an incremental update without changing code?

**Comment by eddyxu** [comment]
Yes, IVF_PQ works with delta update as well. 

When updating after the index was created, the index will degrade over the time, you wanted to run optimization or re-create index over the dataset to maintain performance.

**Comment by eddyxu** [comment]
closed as answered.
