### ISSUE TITLE
Authenticating with S3 from local machine

### ISSUE THREAD

**Issue by HeskethGD** [lancedb/lancedb#712]
I am trying to authenticate to a vector store on S3. It works from inside AWS Lambda but not when running locally. Looking at the source code I'm not sure if it is using AWS credentials. Is it possible to pass credentials? I have confirmed my authenticated user can access the folder on s3 using boto3 so they do have permissions but I guess they are not being used. Here's what I was trying:

```
import lancedb

S3_BUCKET_NAME = "my-bucket-name"
db = lancedb.connect(f's3://{S3_BUCKET_NAME}')

table_name = "my-table
tbl = db.open_table(table_name)
```

Here's the error msg:

OSError: When getting information for key 'my-table.lance' in bucket 'my-bucket-name': AWS Error ACCESS_DENIED during HeadObject operation: No response body.

**Comment by changhiskhan** [comment]
how have you setup the credentials on the host where you're running that code? Authentication is done in Rust, which should pick up the whole credential chain. Just to double check, are you able to try setting the credentials in the standard envvars and see if that changes things?

**Comment by HeskethGD** [comment]
This code is running on my laptop. I have not done anything explicitly to set credentials in the code as I couldn't see any docs on it. I am writing Python and have never used any Rust. I normally authenticate using AWS SSO and if I use boto3 to query s3 it will pick up my creds. When you say set the creds in standard environment variables do you mean access key and secret, i.e. not SSO I guess?

**Comment by changhiskhan** [comment]
@wjones127 does object store work well with aws sso? (And does the lance credential provider pick that up)?

**Comment by BertrandRenault** [comment]
Hello,

Same issue here, to access a public bucket on S3 compatible storage (Minio)
The fllowing code works fine:
```
import boto3
client = boto3.client("s3", endpoint_url="https://<my_minio_url>",)
client.list_objects_v2(Bucket="my_public_bucket")
```
and this code too works fine:
```
import boto3
from s3path import S3Path, register_configuration_parameter
minio_ressource = boto3.resource('s3', endpoint_url="https://<my_minio_url>")
minio_bucket_path = S3Path("/my_public_bucket")
register_configuration_parameter(minio_bucket_path, resource=minio_ressource)
print([d.as_uri() for d in minio_bucket_path.glob("*/*.lance")])
```
but the following:
```
import lancedb
ds = lancedb.connect("s3://my_public_bucket/my_lance_tables_dir")
ds.table_names()
```
raises
OSError: When listing objects under key 'my_lance_tables_dir' in bucket 'my_public_bucket': AWS Error INVALID_ACCESS_KEY_ID during ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

I also tried with credentials set in env. vars (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,...) or in ~/.aws/credentials (it's a public bucket but tried anyway)

What is weird about this, it's this code worked a couple of mounths ago, but even by reverting to older lancedb version I now always have this issue. So maybe it's not really related to lancedb, but it works with direct boto3 or S3Path access

**Comment by wjones127** [comment]
@BertrandRenault For connecting to minio, have you set both `AWS_ENDPOINT` and `AWS_DEFAULT_REGION`?

```shell
export AWS_ENDPOINT=https://<my_minio_url>
export AWS_DEFAULT_REGION=us-east-1
```

https://lancedb.github.io/lance/read_and_write.html#s3-compatible-stores

**Comment by BertrandRenault** [comment]
Thans a lots, I had this set before but it was changed from AWS_ENDPOINT to ENDPOINT_URL...
It now work perfectly, thanks again

**Comment by HeskethGD** [comment]
Why was this closed? Does it work with SSO? What was the solution?

**Comment by HeskethGD** [comment]
@wjones127 why was this issue closed? I am still facing the problem and cannot see what the solution is. How can I connect to a LanceDB table in S3 from my local machine for when using AWS SSO?
