### ISSUE TITLE
Feature: Option to turn off search syntax in FTS

### ISSUE THREAD

**Issue by pchalasani** [lancedb/lancedb#769]
### SDK

Python

### Description

Currently when doing 
```
tbl.search(query).to_pandas()
```
or similar, if `query` happens to contain a string that looks like a search syntax and the syntax is wrong, we get an error. E.g. I could be trying to match a query from the user that just happens to look like `"they could have been dogs OR cats"`, and this causes a syntax error. If we change "OR" to lower-case "or", there's no error. 

Maybe this search syntax error can be turned off entirely or an option given to disable syntax checking.

The FTS looks like it's serving a dual purpose: (a) deliberate search queries composed carefully adhering to syntax, and (b) blindly using  a text fragment to get match relevant docs.
In case of (a) the syntax check makes sense, but not in case (b).
We need an option to distinguish (a) from (b) or just default to support (b).

**Comment by changhiskhan** [comment]
Yeah I think there should be query options. Also have you tried quoting the input?

**Comment by pchalasani** [comment]
Haven't but my current workaround is to lower-case all OR AND NOT, and then it's not interpreted as a search syntax.

**Comment by changhiskhan** [comment]
Lmk what you think of the solution presented in #788. Basically if you quote the input, e.g., `table.search('"they could have been dogs OR cats"')`, it should convert it into a phrase query so it skips the syntax checking.

**Comment by pchalasani** [comment]
@changhiskhan do we have to worry about what happens if there's a single quote in the string already, e.g. if the string is `"the cats OR dogs were not really 'pets' at all"` -- will escaping be done automatically? If this is not an issue then this is a good fix!

**Comment by changhiskhan** [comment]
let me add an additional test case

**Comment by changhiskhan** [comment]
nested quoting should work fine (see the new unit tests in that PR).

**Comment by pchalasani** [comment]
Another search syntax issue arose, which can't be fixed via quoting, please see #797
