### ISSUE TITLE
docs: Add basic docs for the Rust API

### ISSUE THREAD

**Issue by prrao87** [lancedb/lancedb#781]
### Description

There aren't any docs for the Rust API in the docs page, even though [`vectordb`](https://docs.rs/vectordb/0.4.2/vectordb/) crate exists. It would help showcase to users how to interface with LanceDB via Rust.

The docs would go in a separate section of [mkdocs.yml](https://github.com/lancedb/lancedb/blob/31f614ac0332495b4308b4c3a636e51fef40e7f1/docs/mkdocs.yml#L177C6-L177C6) called "🦀 Rust", placed below the JavaScript reference.

**Comment by prrao87** [comment]
Could you clarify a bit more on what "basic docs on the homepage" involves? Would it just be a single paragraph in the API reference page that links out of the LanceDB docs, without any code examples?

But yeah I can totally see a lot of folks first hitting crates.io and docs.rs first, so it doesn't make too much sense to duplicate the work. I think a couple code examples would be nice within the LanceDB docs too tho.

**Comment by wjones127** [comment]
> Could you clarify a bit more on what "basic docs on the homepage" involves? Would it just be a single paragraph in the API reference page that links out of the LanceDB docs, without any code examples?


By homepage, I meant the homepage of the API reference: https://docs.rs/vectordb/latest/vectordb/

So I would keep all the Rust docs, including any user guides, inside that Rust API reference.

> I think a couple code examples would be nice within the LanceDB docs too tho.

Indeed it could be nice. But IMO that's more work to maintain, and so it would make sense to wait until we have a larger team supporting the Rust API.
