### ISSUE TITLE
docs: Move SIFT/GIST-1M benchmarks over from Lance repo to LanceDB repo

### ISSUE THREAD

**Issue by prrao87** [lancedb/lancedb#786]
### Description

The SIFT/GIST-1M benchmarks are important and have been documented via a blog post recently. These also directly utilize the LanceDB repo (unlike the other benchmarks that utilize the Lance API and operate directly on Lance datasets) -- so it would make sense to move these benchmarks over to a new `benchmarks` directory within the LanceDB repo instead.

This way, the benchmark code can then be referenced via the documentation page that will be added in #787.

**Comment by QianZhu** [comment]
We use dbpedia dataset and have benchmark numbers published in our enterprise docs.
