### ISSUE TITLE
Document "no limit" behavior for LanceQueryBuilder

### ISSUE THREAD

**Issue by dconathan** [lancedb/lancedb#796]
### Description

https://github.com/lancedb/lancedb/blob/121687231c2979844d3b3bc4662c848007cd1e02/python/lancedb/query.py#L263

The type annotation for `LanceQueryBuilder.limit()` says limit must be an int and there's no mention of what you should pass if you want "no limit" (it's `None` ... a user might think you need to pass in `limit=-1`?).  Type annotation should be changed to `Optional[int]` and `None` behavior should be documented accordingly.

Somewhat related - it is a little non-intuitive that the default behavior is `limit = 10` as opposed to no limit.

**Comment by changhiskhan** [comment]
The API is focused on search so a limit is always required in that case. And we just set a limit of 10 to prevent users from accidentally shooting themselves in the foot. E.g., BI tools always have a limit that's on by default (but that you can manually turn off).

On the documentation gap, that's a good point. Let's keep this issue open and we'll make a fix (also open to PRs if you're interested).
