### ISSUE TITLE
Feature: make Rust SDK consistent with Python / NodeJS

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#842]
### SDK

Rust

### Description

* `Database` => `Connection`
* global `connect()` function that can accept `uri`, `api_key/http_overwride`.
* Make sure `open_table/drop_table` and `Table` signatures are compatible between languages
* Add examples in doc site to use Rust end-to-end.

**Comment by westonpace** [comment]
This is being superseded by https://github.com/lancedb/lancedb/issues/996
