### ISSUE TITLE
Feature: make Python SDK based on Rust SDK

### ISSUE THREAD

**Issue by wjones127** [lancedb/lancedb#849]
### SDK

Python

### Description

This would fix several issues with object storage, as we can remove reliance on pyarrow filesystems:

* https://github.com/lancedb/lancedb/issues/485
* https://github.com/lancedb/lancedb/issues/673
* S3 Express support

However, there are some complexities to consider:

1. What would `Table.to_lance()` do? Many workflows rely on dropping down to the Lance level. The simplest thing to do would be pass on the uri and version. This might miss some things like the dynamodb configuration and will definitely drop the metadata cache. In addition, if pylance is needed as a dependency we will double the required binary size for LanceDB.
2. How will we handle FTS indices? Related: https://github.com/lancedb/lancedb/issues/672

Related:

* https://github.com/lancedb/lancedb/issues/842
* https://github.com/lancedb/lancedb/issues/534

### Sub-tasks

 - [x] #997

**Comment by westonpace** [comment]
> In addition, if pylance is needed as a dependency we will double the required binary size for LanceDB.

Would it be possible to add `lance` as a submodule to `lancedb` and then have the python package include `pylance`, not as a dependency, but as a sort of "nested port"?

**Comment by wjones127** [comment]
> Would it be possible to add lance as a submodule to lancedb and then have the python package include pylance, not as a dependency, but as a sort of "nested port"?

You'd have to find some way to merge the binaries. Likely difficult to automate.

I think we should just make sure pylance is an optional dependency and raise an error if `to_lance` is called and it's not installed.

**Comment by westonpace** [comment]
The async API for lancedb is now live and based on the rust SDK.  There is still work to do to get a feature complete API but that is covered in more detail in https://github.com/lancedb/lancedb/issues/996 I am closing this issue.
