### ISSUE TITLE
bug(node): LanceDBError: LanceError(IO): No such file or directory (os error 2)

### ISSUE THREAD

**Issue by mrddter** [lancedb/lancedb#856]
### LanceDB version

0.4.3

### What happened?

impossible to run lancedb on node.js v20.10.0, this error is fired:

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: LanceDBError: LanceError(IO): No such file or directory (os error 2), /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-core-0.9.6/src/io/local.rs:50:5]

any suggestion?

### Are there known steps to reproduce?

```
'use strict'
import lancedb from 'vectordb'

async function example() {
  const db = await lancedb.connect('./data/sample-lancedb')
  const data = [
    { id: 1, text: 'Cherry', type: 'fruit' },
    { id: 2, text: 'Carrot', type: 'vegetable' },
    { id: 3, text: 'Potato', type: 'vegetable' },
    { id: 4, text: 'Apple', type: 'fruit' },
    { id: 5, text: 'Banana', type: 'fruit' },
    { id: 6, text: 'Frodo', type: 'person' },
    { id: 7, text: 'Jhon', type: 'person' },
    { id: 8, text: 'Kiwi', type: 'fruit' }
  ]

  await db.dropTable('food_table')
  const table = await db.createTable('food_table', data)

  console.log('table? ' + table)
}

example().then((_) => {
  console.log('Done!')
})

```

**Comment by wjones127** [comment]
It looks like you might be dropped a table before it even exists. What happens if you skip calling `await db.dropTable('food_table')`?

**Comment by changhiskhan** [comment]
we should probably port over the `if_missing` parameter from python to nodejs so dropping a non-existent table doesn't throw. And probably add `exist_ok` to createTable in nodejs as well so drop_table is not necessary

**Comment by mrddter** [comment]
yes it is the dropTable, thanks a lot!
For now, I can use db.tableNames() to check if exists.

I'm trying to use node-llama-cpp with vectordb and it seems to work 
Thanks again, this project is very interesting. Compliments.
