### ISSUE TITLE
Docs for GPU based indexing

### ISSUE THREAD

**Issue by QianZhu** [lancedb/lancedb#864]
### Description

We need to expose package version, parameters that users can tune (along with the impact of tuning) to customers.

example: https://github.com/lancedb/lancedb/issues/767 - user ran out of memory from indexing. The doc should provide guidance on asking user to check pyarrow version, multiprocessing start method and instructions on how to tune the shuffler parameter

**Comment by AyushExel** [comment]
I think this page addressed this https://lancedb.github.io/lancedb/ann_indexes/ ?
Please reopen if there's something else needed
