### ISSUE TITLE
Feature: drop non exist table should return meaningful error message

### ISSUE THREAD

**Issue by eddyxu** [lancedb/lancedb#884]
### SDK

Rust

### Description

How to reproduce
```
db.create_table("my_table", data,...);
db.drop_table("MyTable").await.unwrap();
```

```
thread 'main' panicked at rust/vectordb/examples/simple.rs:50:36:
called `Result::unwrap()` on an `Err` value: Lance { message: "LanceError(IO): No such file or directory (os error 2), /Users/lei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.9.10/src/local.rs:50:5" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by changhiskhan** [comment]
i think trying to open a non-existent table has the same issue

**Comment by BubbleCal** [comment]
- [ ] map `ErrorKind::NotFound` to `Error;:NotFound`
- [ ] Handle the `Error::NotFound` and map it to `TableNotFound` while dropping a table not exists
- [ ] Upgrade the lance lib for lancedb

**Comment by BubbleCal** [comment]
> i think trying to open a non-existent table has the same issue

I tried this and it works fine (the error is `TableNotFound`), will add tests for both of the cases

**Comment by BubbleCal** [comment]
#1038 has added a test for this and it passed
