### ISSUE TITLE
Conversion error when `where` filter does not return values

### ISSUE THREAD

**Issue by matheus-donato** [lancedb/lancedb#905]
### LanceDB version

v0.5.0

### What happened?

I received the following error when filter my db. In this case I tried to convert to a list, but the same error occurs for any other conversion.

**self.id_type:** is a string that represents a name of column
**id:** is a id string that represents a id of item in table

# Error
```
Io error: Internal error: Unexpected result from predicate evaluation: Scalar(Boolean(NULL)).
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

# Code
`self.tbl.search().where(f"{self.id_type} = '{id}'").to_list()`

**Comment by chebbyChefNEQ** [comment]
Hi, could you also provide us with the table schema and the values of `self.id_type` and `id`. Cheers

**Comment by QianZhu** [comment]
closed due to inactivity.
