### ISSUE TITLE
bug(node): LanceDBError: LanceError(IO): Read-only file system (os error 30)

### ISSUE THREAD

**Issue by KrishnaManohar1997** [lancedb/lancedb#927]
### LanceDB version

v0.4.8

### What happened?

Facing the following error when trying to connect to a Local database using the [Typescript Vectorb package](https://github.com/lancedb/lancedb?tab=readme-ov-file#quick-start) inside vscode extension development.

### Error
```
LanceDBError: LanceError(IO): Read-only file system (os error 30),
 /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-io-0.9.12/src/object_store.rs:315:13.
```

### Code 
Following code is triggered as part of Vscode Extension startup I'm building
```
import lancedb, {connect} from 'vectordb';

let db: lancedb.Connection;
let indexTable: lancedb.Table;

export async function connectDatabase() {
    console.log("Trying to connect to VectorDB")
    db = await connect('localdb/data')
    console.log("Connected to VectorDB");
}
```

### Steps I've followed

1. Used the example code from the [Documentation](https://github.com/lancedb/lancedb?tab=readme-ov-file#quick-start)
2. The same has worked for connecting to DB and inserting data in a standalone .ts file.
3. However it fails when the same code is used in the Vscode Extension Development environment with the error shared earlier.

### What I have already tried?
Tried opening Vscode as Admin by executing sudo code - Still the same issue
Creating Files isn't an issue inside Vscode Extension, I have already tried another database vectra which was creating files as part of vscode extension code.
chmod -R 777 /Users/my/code/folder

Sharing the query I have shared on Stackoverflow for the same
https://stackoverflow.com/questions/77939498/vscode-extension-vectordb-lancedberror-lanceerrorio-read-only-file-system

### Are there known steps to reproduce?

1. The `connect` function is working in a `.ts` file when executed independently/standalone
2. However the same function is throwing the error as shared earlier when it's part of the Vscode Extension Development environment

**Comment by wjones127** [comment]
Closing this for now. I think we'd like to seek out a community developed VS code extension that is successful, and then others could use that as a reference. Tracking in https://github.com/lancedb/lancedb/issues/1849
