### ISSUE TITLE
bug(python): Can't pickle local object 'Vector.<locals>.FixedSizeList'

### ISSUE THREAD

**Issue by kimusaku** [lancedb/lancedb#938]
### LanceDB version

v0.5.3

### What happened?

I tried to pickle a LanceModel object containing Vector:

```python
from lancedb.pydantic import LanceModel, Vector
import pickle

class MyModel(LanceModel):
  vector: Vector(2)
  foo: str

model = MyModel(vector=[0.0, 0.0], foo="bar")
pickle.dumps(model)
```

then got an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Can't pickle local object 'Vector.<locals>.FixedSizeList'
```

**Comment by changhiskhan** [comment]
with pydantic rather than pickling the object, you can save the json instead. 

`model.model_dump_json()` => gives you a json string representation of the model instance
`MyModel.model_validate_json()` gives you an instance from the json str

e.g., 
```python
In [11]: MyModel.model_validate_json(model.model_dump_json())
Out[11]: MyModel(vector=FixedSizeList(dim=2), foo='bar')
```

**Comment by kimusaku** [comment]
Thanks. I will use `model_dump_json()` instead of pickle.
