### ISSUE TITLE
Feature: Implement Late Interaction Multi-Vector Search

### ISSUE THREAD

**Issue by aretrace** [lancedb/lancedb#945]
### SDK

Python

### Description

Looks like [stanford-futuredata/ColBERT](https://github.com/stanford-futuredata/ColBERT) is a compelling method for IR, I believe that LanceDB could benefit from a native implementation. [Vespa](https://blog.vespa.ai/semantic-search-with-multi-vector-indexing/) has an implementation.

**Comment by ericfeunekes** [comment]
Looks like this is already tracked at #973.

**Comment by aretrace** [comment]
I guess I was five days too early 😢
