### ISSUE TITLE
Feature: Please add support for ColBERT Embedding function

### ISSUE THREAD

**Issue by sungkim11** [lancedb/lancedb#973]
### SDK

Python

### Description

Vespa supports ColBERT. Can you add support for ColBERT as well?

**Comment by changhiskhan** [comment]
could you provide more details on your use case? Would love to know why ColBERT is important / valuable for you.
@AyushExel has already added the ColBERT reranker, does that meet your needs?

**Comment by sungkim11** [comment]
That will work. I will try that. Thank you.

**Comment by AyushExel** [comment]
I'm re-opening this one as users might also want to use colbert and colbert v2 models for embedding the data too.

**Comment by AyushExel** [comment]
This is done - https://lancedb.github.io/lancedb/embeddings/default_embedding_functions/#sentence-transformers
