### ISSUE TITLE
Feature: port python's embedding funtions to Rust

### ISSUE THREAD

**Issue by westonpace** [lancedb/lancedb#994]
### SDK

Rust

### Description

Python has the ability to specify one or more embedding functions on table creation.  These functions will be run whenever data is added (to calculate the embedding for the new rows from the raw data) and whenever a table is queried (to calculate the appropriate embedding from the query).  Adding similar traits into Rust should be straightforward.

However, in python, these embedding functions are also persisted as part of the table and will be present when the table is loaded again in the future.  This will be slightly more complex in Rust and probably require some kind of registry of embedding functions.

**Comment by changhiskhan** [comment]
the main issue is how we'll run the huggingface models. if they all have an onnx representation then this maybe possible

**Comment by westonpace** [comment]
> the main issue is how we'll run the huggingface models. if they all have an onnx representation then this maybe possiblej

My thinking wasn't full compatibility in terms of "available models and libraries".  My thinking is that the rust feature would only allow custom embedding functions initially, and users would need to configure the registry themselves.  E.g. this could be an extension port for people working with things like https://github.com/rustformers/llm or https://github.com/huggingface/candle

**Comment by universalmind303** [comment]
I'm wondering if these should be compatible across languages? 

as in if i create this table in python
```py

func = get_registry().get("openai").create(name="text-embedding-3-large")
# func = get_registry().get("openai").create(name="text-embedding-ada-002")
class Items(LanceModel):
    text: str = func.SourceField()
    id: int
    price: float
    vector: Vector(func.ndims()) = func.VectorField()

table = db.create_table("python", schema=Items, mode="overwrite")
table.add([
    {"id": 100, "text": "socks", "price": 10.00},
    {"id": 200, "text": "shoes", "price": 20.00},
])
```

then register the same function in rust

```rs
    let embedding = Arc::new(OpenAIEmbeddingFunction::new_with_model(
        "text",
        api_key,
        "text-embedding-3-large",
    )?);

    let db = connect(tempdir).execute().await?;
    db.embedding_registry()
        .register("openai", embedding.clone())?;
```

When the python created table is loaded in rust, should it automatically use this embedding function for the table? I'd assume we'd let the `registry` decide if it's actually the same function, but I wanted clarity on if this is functionality we want to support.

**Comment by westonpace** [comment]
> I'm wondering if these should be compatible across languages?

I think cross-language use cases like this will be rare but possible.  It would be nice to support it if we could.  I think we can state that a user should only register embeddings with the same name if they are the same function.

**Comment by universalmind303** [comment]
I think this is done now via https://github.com/lancedb/lancedb/pull/1308 and https://github.com/lancedb/lancedb/pull/1259
